### ISSUE TITLE
conventional-changelog-cli always appends full changelog to the existing changelog (starting version 3.0.0)

### ISSUE THREAD

**Issue by viktomas** [conventional-changelog/conventional-changelog#1062]
## Problem

Since the 3.0.0 release (https://github.com/conventional-changelog/conventional-changelog/releases/tag/standard-changelog-v3.0.0) the command `conventional-changelog -p angular -i CHANGELOG.md -s ` **started appending a full changelog** (starting from 1st commit in the repository) to the existing changelog.

Example: https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/blob/2c6ca27d328069183fd6725faa01bd003c643efa/CHANGELOG.md (version 3.66.0 was still using `conventional-changelog-cli@2.1.1`, every release after that duplicated the whole changelog).

## Identifying that version 3.0.0 is the first one with the bug

I tested that downgrading to version 2.2.2 (latest before 3.0.0) fixes the issue.

I see that the package responsible for getting the list of tags hasn't been updated in 3 years so it shouldn't be the cause of the problem https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/git-semver-tags/index.js

Can I get a few pointers to help me debug the issue further?

## Reproducing

I can create a simpler example if this is too complex. I encountered the issue in this project https://gitlab.com/gitlab-org/gitlab-vscode-extension

1. `git checkout git@gitlab.com:gitlab-org/gitlab-vscode-extension.git`
2. `cd gitlab-vscode-extension && npm i`
3. `npm run version` (this runs `conventional-changelog -p angular -i CHANGELOG.md -s`)

**Comment by dangreen** [comment]
@viktomas Hi. Could you please see in lock-file or in node_modules which version of conventional-changelog-writer is installed?

**Comment by viktomas** [comment]
@dangreen Thanks for the response 🙏

In `package-lock.json`, I see `conventional-changelog-writer` version `6.0.0` https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/blob/v3.68.0/package-lock.json#L3685

**Comment by ghiscoding** [comment]
probably related to Vite project having similar problems and they downgraded back to v2 for that reason, see this Vite [PR](https://github.com/vitejs/vite/pull/13566). @dangreen you might get more info by talking to the Vite project team
