### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'preMajor')

### ISSUE THREAD

**Issue by Hervera** [conventional-changelog/conventional-changelog#1123]
A problem with the conventional-changelog-conventionalcommits package during the release process. Specifically, it's failing at the conventionalRecommendedBump.js file and throwing a TypeError.

`if (config.preMajor && level < 2) {`

**Comment by dangreen** [comment]
Fixed in https://github.com/conventional-changelog/conventional-changelog/pull/1120
Soon will be released

**Comment by Hervera** [comment]
Great news! Looking forward to the release. Thanks for the update!

**Comment by dangreen** [comment]
https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v7.0.2
