### ISSUE TITLE
conventional-changelog-cli: context file type must json, not support js file

### ISSUE THREAD

**Issue by damingerdai** [conventional-changelog/conventional-changelog#1153]
i found in this pr: [fix: fix semver vulnerability] (https://github.com/conventional-changelog/conventional-changelog/pull/1071) has a big break change that we can not use javescripts file as context file. we must use json file to setup context info.

so my question is that cloud your revert it these change? If no, why and please update it changelog file?

```diff
-  templateContext = JSON.parse(await readFile(relativeResolve(flags.context), 'utf8'))
+ templateContext = require(resolve(process.cwd(), flags.context))
```

**Comment by stevemao** [comment]
Feel free to create a PR to support both
