### ISSUE TITLE
`conventionalcommits` v7 breaks lerna `changelogPreset` integration

### ISSUE THREAD

**Issue by jlipps** [conventional-changelog/conventional-changelog#1157]
[Appium](https://github.com/appium/appium) has a `lerna.json` that has the following field:

```json
{
  "changelogPreset": "conventional-changelog-conventionalcommits"
}
```

Up until the v7 release, this worked as expected. After upgrading to v7+, the `lerna version` process exits immediately (and cleanly) after loading the conventionalcommits package, rather than proceeding with the versioning process.

I'm not entirely sure if this is something that needs to be fixed in lerna, or fixed here, but the change happened here so I'm reporting here.

Currently working around this issue by keeping the version of `conventional-changelog-conventionalcommits` pinned to `6.1.0`.

**Comment by dangreen** [comment]
Duplication of https://github.com/conventional-changelog/conventional-changelog/issues/1116
