### ISSUE TITLE
addBangNotes in conventional-changelog-conventionalcommits does not modify input

### ISSUE THREAD

**Issue by mpsanchis** [conventional-changelog/conventional-changelog#1183]
Hello,

I have seen the [addBangNotes](conventional-changelog-conventionalcommits/utils.js) function, and it doesn't modify the commit it receives as input.

From the way it's used in `conventionalRecommendedBump`, I expected it to modify the commit message, but it only returns `[{ text: noteText }]`, which doesn't even match the [CommitNote](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/src/types.ts#L86) interface.

Shouldn't it modify the commit, adding something like: `{ title: 'BREAKING CHANGE', text: noteText }`? Or maybe it's not a good idea to modify while iterating, and it's better if it returns an `enhancedCommit`, and the rest of `createConventionalRecommendedBumpOpts` works with the enhanced commit instead of the original one?

Correct me if I'm wrong, I might have not understood the process. It's the first time I look at this repo.

Cheers!

**Comment by dangreen** [comment]
@mpsanchis Hi. Thanks for your comment! These changes are not released yet, and refactoring is in progress. I will check these and fix later.

**Comment by mpsanchis** [comment]
Wow thank you for the super fast reply :)
