### ISSUE TITLE
Plans to release newer versions of `packages/conventional-commits-parser`?

### ISSUE THREAD

**Issue by NatPRoach** [conventional-changelog/conventional-changelog#1222]
Hi all, seems that `conventional-commits-parser` versioning hasn't been released for a bit and I was wondering if there was a release planned anytime soon?
The last time the version no was bumped was ~8 months ago, but there have been several major refactors since, several of which look quite useful to some of the things I'm working on.
Thanks in advance!

**Comment by dangreen** [comment]
https://github.com/conventional-changelog/conventional-changelog/pull/1215#issuecomment-1997927931
