### ISSUE TITLE
types for conventional-changelog-conventionalcommits

### ISSUE THREAD

**Issue by tisonkun** [conventional-changelog/conventional-changelog#1260]
It seems there is no type definitions for conventional-changelog-conventionalcommits. What do the maintainers of this repo think on this topic?

**Comment by dangreen** [comment]
@tisonkun Hi. Typically, presets are loaded using [preset-loader](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-preset-loader), so there is no need to have typings in presets.

**Comment by ciltocruz** [comment]
After the update 2 days ago, my changelog no longer divides commits by type. I have not found that any changes need to be made to the configuration... What happened?

In the final summary the group title does appear correctly, but when the changelog.md is written, it is not divided.

```
"commitGroups": [
    {
      "title": ":bug: Bugs :bug:",
      "commits": [
        {
          ...
        }
      ]
    },
```

When I downgraded to version 7, everything worked again.

**Comment by dangreen** [comment]
@ciltocruz Hi. Please open new issue with your problem described. Also please provide minimal repo with reproduction.
