### ISSUE TITLE
Revert commit is not triggering release version

### ISSUE THREAD

**Issue by gutofoletto** [conventional-changelog/conventional-changelog#1261]
Hello

I am using the `conventionalcommits` preset and it seems the `revert: lorem ipsum` message is not triggering a new release version as you can see on the image below:

<img width="1100" alt="Screenshot 2024-05-03 at 18 18 18" src="https://github.com/semantic-release/commit-analyzer/assets/1004681/64ff85f9-45c8-489c-832f-661fdef5c20d">

It's weird because that's [the way the conventional commits documentation suggest you revert a commit](https://www.conventionalcommits.org/en/v1.0.0/#how-does-conventional-commits-handle-revert-commits).

<img width="972" alt="image" src="https://github.com/semantic-release/commit-analyzer/assets/1004681/32b84a75-b54b-44ce-903b-13ded1daa419">

Do you guys have any insights on this?

**Comment by dangreen** [comment]
@gutofoletto Hi. According to the source code and tests revert commit message should satisfy `/^(?:Revert|revert:)\s"?([\s\S]+?)"?\s*This reverts commit (\w*)\./i` regexp. Examples:

```
Revert "feat: default revert format"'

This reverts commit 1234.
```
or
```
revert: feat: custom revert format

This reverts commit 5678.
```

Feel free to create pull request with modifications.

**Comment by gutofoletto** [comment]
Thanks @dangreen. Adding the commit description as you suggested worked. 
I just think it's weird that it does not follow the suggestion from the conventional commits spec.
Maybe we should add an example to the docs?
