### ISSUE TITLE
republish `@conventional-changelog/git-client` as 1.0.1 due to peer dependency issues

### ISSUE THREAD

**Issue by SuperchupuDev** [conventional-changelog/conventional-changelog#1264]
`@conventional-changelog/git-client` sets its peer dependencies at `workspace:^`. 1.0.0 was published a few minutes before the other packages' updates, using the wrong version of the two peer dependencies it uses (as the correct one technically wasn't published yet), making installs of any package that includes `conventional-changelog-core` throw the following warning:

![image](https://github.com/conventional-changelog/conventional-changelog/assets/53496941/36428948-bb52-495d-b24c-d6e145b860bd)

This should be easily fixable by republishing the git client as 1.0.1

**Comment by dangreen** [comment]
Released
