### ISSUE TITLE
Question: with `conventional-changelog-recommended-bump` v10 how do I provide a custom preset?

### ISSUE THREAD

**Issue by favna** [conventional-changelog/conventional-changelog#1266]
Hi there,

Before with v9 of the library it was possible to provide a custom template through options like seen here: https://github.com/favware/cliff-jumper/blob/ab8d611813a18efedfdba0df07ccfb98005fbaa3/src/commands/get-conventional-bump.ts#L18-L112. However with v10 all these options are gone and only `loadPreset` is left. How can I ensure that my library can still use the custom preset with v10?

For the most part my custom preset is the same as the `angular` preset, with the exception that I have provided a `breakingHeaderPattern` to `config.parserOpts` so I would also accept a way to use the Angular preset but override that option only.

That said, assuming that would be through `classInstanceOfBumper.getPreset` / `.preset`, those are completely untyped in the published bundle of the package so that doesn't help much either
`bumper.d.ts`:
```ts
export declare class Bumper {
    private readonly gitClient;
    private preset;
    private whatBump;
    private tagGetter;
    private commitsGetter;
    constructor(cwdOrGitClient?: string | ConventionalGitClient);
    private getLastSemverTag;
    private getCommits;
    private getPreset;
```

**Comment by dangreen** [comment]
@favna Hi.

```js
new Bumper().commits({}, parserOpts).bump(whatBump)
```

**Comment by favna** [comment]
@dangreen And what happened to the `path` (https://github.com/conventional-changelog/conventional-changelog/blob/ad633d9d81f66ef80d7f77832a264cb0c5b971ef/packages/conventional-recommended-bump/index.js#L57) and `lernaPackage` (https://github.com/conventional-changelog/conventional-changelog/blob/ad633d9d81f66ef80d7f77832a264cb0c5b971ef/packages/conventional-recommended-bump/index.js#L48-L49) options that were in `bump` before?

**Comment by dangreen** [comment]
@favna 

Sorry for blind spots in documentation, I will fix that.

```js
new Bumper()
  .commits({
    path: '...'
  }, parserOpts)
  .tag({
    prefix: packagePrefix(lernaPackage)
  })
  .bump(whatBump)
```

[bumper.commits(params: GetCommitsParams & Params, parserOptions?: ParserStreamOptions): this](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#bumpercommitsparams-getcommitsparams--params-parseroptions-parserstreamoptions-this)

https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/git-client/src/types.ts#L1-L29

[bumper.tag(paramsOrTag: GetSemverTagsParams & Params | string): this](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#bumpertagparamsortag-getsemvertagsparams--params--string-this)

https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/git-client/src/types.ts#L44-L57

https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/conventional-recommended-bump/src/bumper.ts#L22

https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/git-client/src/ConventionalGitClient.ts#L15-L26
