### ISSUE TITLE
Update related dependencies

### ISSUE THREAD

**Issue by btea** [conventional-changelog/conventional-changelog#1274]
Currently, using pnpm to install dependencies will result in the following warning message.

![image](https://github.com/conventional-changelog/conventional-changelog/assets/24516654/22fa99cf-38b8-4211-a5ec-bae05884f9a0)

**Comment by dangreen** [comment]
@btea Hi. You need to run `pnpm upgrade`. This was fixed in https://github.com/conventional-changelog/conventional-changelog/releases/tag/git-client-v1.0.1

**Comment by btea** [comment]
Thank you for your quick response. 👍
