### ISSUE TITLE
Bug: `BREAKING CHANGE:` is not read correctly in footer when prepended with `------`

### ISSUE THREAD

**Issue by kddsultan** [conventional-changelog/conventional-changelog#1280]
## Current

```sh
feat: test message

---------

Co-authored-by: Mee <me.e@me.com>

BREAKING CHANGE:  test
```

When used with `semantic-release`, the `commit-analyzer` does not read the keyword `BREAKING CHANGE:` and the resulting version or the change-log is incorrect. 

## Expected 

With the above message, there should be parsed as a major version bump and the message should be part of the change log

**Comment by dangreen** [comment]
@kddsultan Hi. It's incorrect format of commit.

Correct format:

```
feat: test message

BREAKING CHANGE:  test

---------

Co-authored-by: Mee <me.e@me.com>
```

**Comment by kddsultan** [comment]
> @kddsultan Hi. It's incorrect format of commit.
> 
> Correct format:
> 
> ```
> feat: test message
> 
> BREAKING CHANGE:  test
> 
> ---------
> 
> Co-authored-by: Mee <me.e@me.com>
> ```

Thank you for your explanation, for now closing as the format is accepted as a common format
