### ISSUE TITLE
git-semver-tags should get its tags from git tag instead of git log

### ISSUE THREAD

**Issue by Arcticon** [conventional-changelog/conventional-changelog#1286]
## Problem
The current implementation uses `git log` to retrieve information about git tags. This works fine for any workflow where one tags the `default branch`. Other workflows such as version branches, where additional tags are created, are not supported.

Others have already pointed this out: #688 #824 

The Readme also points out that:
> Get all git semver tags of your repository in reverse chronological order. [...] If two tags on one commit, the order is not guaranteed

This can be resolved by simply using `git tag` instead of `git log`.

## Performance
Ive also run some benchmarks and get these results:
```bash
$ hyperfine -m 100 'git log --decorate --no-color --date-order | grep -E "tag:\s*(.+?)[,)]"' 'git tag -l --sort=-v:refname'
Benchmark 1: git log --decorate --no-color --date-order | grep -E "tag:\s*(.+?)[,)]"
  Time (mean ± σ):      25.1 ms ±   2.9 ms    [User: 15.0 ms, System: 11.1 ms]
  Range (min … max):    17.2 ms …  36.0 ms    143 runs
 
Benchmark 2: git tag -l --sort=-v:refname
  Time (mean ± σ):       2.1 ms ±   0.4 ms    [User: 1.5 ms, System: 0.2 ms]
  Range (min … max):     1.6 ms …   6.0 ms    1045 runs
 
Summary
  'git tag -l --sort=-v:refname' ran
   12.01 ± 2.50 times faster than 'git log --decorate --no-color --date-order | grep -E "tag:\s*(.+?)[,)]"'
```
Where `git tag` is about 10-14 times faster than `git log` with a regex `grep`.

## Final Question
Is there a reasoning behind this that i dont see?

**Comment by dangreen** [comment]
@Arcticon Hi! Feel free to open pull request with desired changes!

**Comment by Arcticon** [comment]
Ive checked all possibilities whether `git log` is a suitable alternative or not.
Ive come to the conclusion that it simply does not work with neither a **monorepo** nor a **change in version format** (from vX.Y.Z to X.Y.Z).

However i have found a promising option for the `git log` command: `--all`
> Pretend as if all the refs in refs/, along with HEAD, are listed on the command line as <commit>.

This resolves any issues with tag commits on version branches.

```bash
$ git log --all --decorate --no-color --date-order | grep -E "tag:\s*(.+?)[,)]"
commit xyz (tag: 1.5.0)
commit xyz (tag: 1.4.1)
commit xyz (tag: 1.4.0)
commit xyz (tag: 1.3.0)
commit xyz (tag: 1.2.0)
commit xyz (tag: 1.1.0)
commit xyz (tag: 1.0.0)
$ git log --decorate --no-color --date-order | grep -E "tag:\s*(.+?)[,)]"
commit xyz (tag: 1.3.0)
commit xyz (tag: 1.2.0)
commit xyz (tag: 1.1.0)
commit xyz (tag: 1.0.0)
```

**Comment by Arcticon** [comment]
@dangreen could you please verify the code? :)

**Comment by dangreen** [comment]
@Arcticon As I understood, solution of your issue is just one line from your PR:

https://github.com/conventional-changelog/conventional-changelog/blob/bf2d15bbfc0aecce6d0b9dfef2660b89a2798fad/packages/git-client/src/GitClient.ts#L86

But you can pass that parameter via argument if you need:

```ts
gitClient.getTags({ all: true })
```

For most users all works fine without that parameter. But if we will enable it by default, it will breaking change and can cause issues for some users.

If you need that in `git-semver-tags` package so add this as optional parameter that is disabled by default.

**Comment by Arcticon** [comment]
@dangreen i see.
the issue i am facing is shadowed by the use of [commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version).
[here](https://github.com/absolute-version/commit-and-tag-version/blob/master/lib/latest-semver-tag.js#L6) they are using git-semver-tags and dont expose any possibility to pass additional properties to it.

i will open an issue over there and close this one.
thank you :)
