### ISSUE TITLE
"types" property is missing in package.json

### ISSUE THREAD

**Issue by eladchen-lusha** [conventional-changelog/conventional-changelog#1295]
Hi,

Seems like typescript is unable to pickup type definitions, from what i could tell the package json is missing the "types" field.

For example: 

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/package.json

**Comment by dangreen** [comment]
@eladchen-lusha Hi. conventional-changelog-conventionalcommits is js-only package
