### ISSUE TITLE
Move this repo to an org

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventional-changelog#143]
Hi @btford and @ajoslin , I want to move this repo to https://github.com/conventional-changelog org. It'll be easier for us to manage modules. Thanks.

Ref: https://github.com/bcoe/conventional-recommended-workflow/issues/3#issuecomment-205567858

**Comment by ajoslin** [comment]
:+1: sounds good to me. When would you like to move it?

**Comment by stevemao** [comment]
Now :) I invited you to the org.

**Comment by stevemao** [comment]
@ajoslin Could you contact @btford? :smile:

**Comment by ajoslin** [comment]
I don't have admin access to conventional-changelog, so I can't transfer it.

Let's give @btford at least a day or two to respond before trying alternate forms of communication.

**Comment by stevemao** [comment]
Ok, don't delete any repos :)

**Comment by ajoslin** [comment]
Transferred! Feel free to un-owner me.

**Comment by ajoslin** [comment]
Thanks for all the consistent work on this Steve, by the way. You've done a fantastic job.

**Comment by stevemao** [comment]
Beautiful, thanks Andrew.

**Comment by stevemao** [comment]
> Feel free to un-owner me.

Might do it soon. But if you want to work on this I can always re-add you. Thanks a lot :)
