### ISSUE TITLE
Creating a custom version scheme (e.g. namespaced tags)

### ISSUE THREAD

**Issue by krnlde** [conventional-changelog/conventional-changelog#144]
We are currently using conventional-changelog "as is", which means it creates version tags in the scheme of `major.minor.patch`, but in the current deployment pipeline we need to namespace/prefix the version number like so: `frontend/customer-ui/1.2.3`

I successfully changed the git tagging to the latter, but conventional-changelog still tries to compare un-namespaced versions `1.2.3`.

Are the [previousTag](https://github.com/conventional-changelog/conventional-changelog-core#previoustag) and [currentTag](https://github.com/conventional-changelog/conventional-changelog-core#currenttag) options the key?

Can anyone give an advice on how to configure and use that?

**Comment by stevemao** [comment]
I found a potential problem when I was checking this...

**Comment by krnlde** [comment]
Could you provide some details please?

**Comment by stevemao** [comment]
Well the problem I found is not relevant to this. You need to checkout the docs of https://github.com/conventional-changelog/conventional-changelog-core and https://github.com/conventional-changelog/conventional-changelog-writer. Any default value related to semver tag change to normal tag.

**Comment by krnlde** [comment]
I in fact was looking at those before opening this issue and was mentioning them in my description already.
Since you didn't answer to that, I guess I'll have to figure it out myself? I'll rahter move away from this project. Docs are not helpful, sourcecode is mildly helpful but a pita to go through since the projects are distributed in many repos, community is not helpful. Kthxbye.

**Comment by stevemao** [comment]
Why don't you stand out and improve this? @krnlde

**Comment by krnlde** [comment]
Because I don't understand it. Otherwise this would be a PR rather than an issue.

**Comment by stevemao** [comment]
What I said was the only way to do it. All the defaults and `context` are overwritable. That's what the current structure is. If you take a look at the 100 closed issues here and sub modules, this is the best way I can come up with.
If you wanna customise it it's all possible (as these modules expose lowest possible level apis), but with so many options it definitely takes time to learn.

In fact, a bunch of experienced devs prefer opinionated, zero-config tools and they rather follow the strict angular convention. We have wrapper modules with deadly simple config but doesn't fit your git history.

If you have a better way of doing it suggestions welcome.

**Comment by krnlde** [comment]
I would gladly suggest a better way if I'd only understand the configuration. What *is* `currentTag`, what *is* `previousTag`, does conventional-changelog use these two for comparison or does it just rely on git-semver-tags? What is `version`, does conventional-changelog use this to compare something? The whole thing looks like magic and the docs only explain their naming but not what they actually mean nor do, tbh. If you'd explain it to me, or better give an example option set for this issue I would write up some example repo using this.

**Comment by stevemao** [comment]
They are all under `context`. and you see

> context
See the conventional-changelog-writer docs. There are some defaults or changes:

You firstly need to read `context` under `conventional-changelog-writer` as it states. Then you'll see `context` is

> Variables that will be interpolated to the template. This object contains, but not limits to the following fields.

If your keen to customise your tool, there is a section https://github.com/conventional-changelog/conventional-changelog-writer#context-1. I don't think you'll have to read this section but it helps you to better understand it.

I keep updating the docs so I think the docs has all information you need, but the wording is not the best for sure. 

I don't know if that makes sense?

**Comment by krnlde** [comment]
I don't have access to the writer directly, since `gulp-conventional-changelog` does all these tricks for me.

Having the following gulp task:
```
gulp.task('changelog', function () {
  return gulp.src('CHANGELOG.md', {
    buffer: false
  })
  .pipe(conventionalChangelog({
    preset: 'angular'
  }))
  .pipe(gulp.dest('./'));
});
```

Aside to the `preset` options, which options do I have to provide to make it work comparing the two versions:
* `frontend/customer-ui/1.2.3`
* `frontend/customer-ui/1.2.4`

**Comment by stevemao** [comment]
> I don't have access to the writer directly

The fifth arg is the `writerOpts`, as its stated on the docs.
> See the conventional-changelog docs.

Meaning it's exactly the same as `conventional-changelog`, which is common for wrapper modules.

> Aside from the preset options, which options do I have to provide to make it work comparing the two versions:

Refer back to my previous comments.

**Comment by krnlde** [comment]
Dude, if you want me to read the friendly manual, I did. And I didn't understand how to plug all the options, since I'm not into the code of `conventional-changelog`, `conventional-changelog-writer`, `conventional-changelog-core` and finally `gulp-conventional-changelog`. But you do, since you wrote most of these. That's why I'm asking [you]. So: do or do you not know the answer to my issue and would you like to share it with me?

**Comment by stevemao** [comment]
`conventional-changelog-writer` is all about template and context, all the options are to help to generate the context you want. The default ones are the most common ones you are likely to use (including `currentTag` etc).
I really don't know what's not clear here.
All you need to do is overwrite the default `currentTag` with the value you want. Here `currentTag` defaults to a semver tag but you need just a normal tag.

**Comment by krnlde** [comment]
So this should do the trick?

```js
gulp.task('changelog', function () {
  return gulp.src('CHANGELOG.md', {
    buffer: false
  })
  .pipe(conventionalChangelog({
    preset: 'angular',
    previousTag: 'frontend/customer-ui/1.2.3',
    currentTag: 'frontend/customer-ui/1.2.4'
  }))
  .pipe(gulp.dest('./'));
});
```

**Comment by krnlde** [comment]
Are there any further suggestions?

**Comment by zry754331875** [comment]
@krnlde I have the same needs as you, and your problem can be solved by tagPrefix. But my problem is that the tag ‘1.3.0.20191226’ I defined is not a Semver Tag, which caused conventionalChangelog to be generated from the first commit. How to support custom tags? Or how to rewrite the comparison method?
