### ISSUE TITLE
Question & Suggestion

### ISSUE THREAD

**Issue by AdamWillden** [conventional-changelog/conventional-changelog#147]
First, well done for making this. Love the idea and encourages (requires) commit message standardisation which is great for working in teams.

Q. Does this only work with hosts or can it determine the change log from version tags? Does it/Should it support locally hosted gitlab repos (which is ultimately what I need)?

I've noticed though reading the related repos there's not even a single sentence to describe what each repo is meant to do. Yes, some are relatively self explanatory but some explanation and a glance of how it works would be a great addition! I've come here because I use aurelia which is using quite an outdated version of this plugin. It took me a long time to understand what was needed as a result.

**Comment by stevemao** [comment]
All the `context` are optional. Meaning you could config them as much as possible. The modules intelligently guess what the values they meant to be based on git and `package.json`.

**Comment by stevemao** [comment]
I'm not completely sure what you are asking for or what we could do here. But PR welcome!

**Comment by AdamWillden** [comment]
Thanks for the reply - I missed the notification 3 days ago!

Well the issue is that it took me quite some time to figure out how all the `conventional-changelog` subcomponents interact, how I needed to use it:

"Wow there are a few components here" -> "Where should I start?" -> "Oh, what does this one do?" -> "Right, err, so how is this used with respect to the others?"  **Rinse, get a bit confused and repeat.**

I still don't really understand if it can handle everything I'm thinking of. So it'd be great if the documentation gave a clue as to how the subcomponents fit into the conventional-changelog 'ecosystem'. I think the best thing would be to just draw up a simple diagram - a picture tells a thousand words after all!

By subcomponents I mean all these:
* usage (cli/gulp/grunt and the 'packaged' standard-version)
* presets (angular, jquery, etc.)
* core
* parser
* bump & recommended-bump
* writer
* releaser

I'm not sure how the core fits into it all other than it's named core so it's probably used by a few things. As a user I assume I don't really care what that does however but it'd be nice to know that.

**Comment by stevemao** [comment]
Say if you are using `conventional-changelog-cli`, the things you need to understand are linked in the readme. EG: you want to config it, and you should see a link to `conventional-changelog`, and you'll probably find a link to `conventional-changelog-writer`. So the entry point is the module you are currently using.

**Comment by stevemao** [comment]
Also the meta repo is for discussion, the recipes repo is for demos in the future.

**Comment by stevemao** [comment]
Does it make sense @AdamWillden? Feel free to open a pr to improve the docs.

**Comment by AdamWillden** [comment]
Yes what you said makes sense. I haven't looked into this since to get the understanding I'd require for a PR or anything like that.

I plan to use your fine work as part of the infrastructure for a new component library at work. We haven't yet started work on it yet though and I'd probably revisit this when we do.

Feel free to close this issue. I can't promise a PR any time soon!

**Comment by stevemao** [comment]
I recommend you to use [standard-version](https://github.com/conventional-changelog/standard-version)
