### ISSUE TITLE
Can't create proper changelogs

### ISSUE THREAD

**Issue by CreativeZoller** [conventional-changelog/conventional-changelog#148]
I checked the "recipes" and found this package. It seems to be very good but I have some untrusty issues after reading 70% of closed issues here. So I just ask and we'll see... 

Now with this code
```
gulp.task('changelog', function () {
  return gulp.src('CHANGELOG.md', {
    buffer: false
  })
    .pipe(conventionalChangelog({
        preset: 'angular'
      }))
    .pipe(gulp.dest('./'));
});
```
It will generate a changelog.md with the following content only:
```
<a name="0.1.4"></a>
## [0.1.4](https://github.com/xxx/yyy/compare/0.1.3...v0.1.4) (2016-06-03)



<a name="0.1.3"></a>
## [0.1.3](https://github.com/xxx/yyy/compare/0.1.2...v0.1.3) (2016-06-03)
```
My problem is I have no idea how to configure to get all my comments inside it, as I see in my file history of github commits. So I would like to create a task to generate changelog fle like this in your repo ([conventional-changelog/readme.md](https://github.com/conventional-changelog/conventional-changelog/blob/master/CHANGELOG.md)). Could you give me some suggestions, guidelines?

**Comment by stevemao** [comment]
I'd suggest you to use [standard-version](https://github.com/conventional-changelog/standard-version), as it's recommended in README.
