### ISSUE TITLE
Bitbucket or GitLab typed links for self-hosted installations

### ISSUE THREAD

**Issue by cschroeter** [conventional-changelog/conventional-changelog#152]
How do I enforce conventional-changelog to use link style format for other repositories than GitHub, if the hostname doesn't contain gitlab.com or bitbucket.com ?

**Comment by stevemao** [comment]
It uses [conventional-changelog-writer](https://github.com/conventional-changelog/conventional-changelog-writer) to output based on your templates. So you can config there.

**Comment by stevemao** [comment]
@cschroeter  what exactly are you asking for?
