### ISSUE TITLE
Usage with git flow?

### ISSUE THREAD

**Issue by bguiz** [conventional-changelog/conventional-changelog#153]
Hi,

I like the features in this package, and I would like to know how this can be used in conjunction with git flow (the command line edition). Currently my release process is:

```
git flow release start 1.2.3
vim package.json #manually version to 1.2.3
git commit package.json -m "bump version"
git flow release finish 1.2.3
#accept default commit message populated by git flow for merge commit
#type "release v1.2.3" for the tag message
git push origin master --tags #pushes tag named "v1.2.3"
git push origin develop
```

It involves:

- typing the version number a total of 4 times
- don't get the version number decided automatically (whether it is a patch or minor)
- don't get the tag message auto-populated with the commit messages from what has changed since the last release
- have to type many commands

I'm using git flow as a general branching strategy tool, not just for releases, and would like to continue doing so. I would like for git flow to still control the anything to do with branching and committing, and use conventional-changelog for determining what the next version number should be, and auto-populating the tag commit message.

Is there some combination of command line options or configuration that will allow me to achieve this?

Thanks!

**Comment by stevemao** [comment]
Is it the same as https://github.com/conventional-changelog/conventional-github-releaser/issues/21?

**Comment by bguiz** [comment]
@stevemao thanks for the link. I have read through that issue, but I am still unclear as to how to use this project in conjunction with git flow. I am fairly familiar with git flow, but not at all to conventional-changelog so I don't really follow what's being discussed in that thread.

**Comment by bguiz** [comment]
Could you perhaps provide an example usage with git flow?

**Comment by stevemao** [comment]
@bguiz I'd suggest you to use `[standard version](https://github.com/conventional-changelog/standard-version)` :)

**Comment by stevemao** [comment]
It shouldn't matter what git extension you are using, as long as you follow the process of standard-version it should work :)

**Comment by benmarten** [comment]
standard version is not at all gitflow compliant

**Comment by hbetts** [comment]
@benmarten would you please consider filing issues with `standard-version` to bring up each issue that inhibits its use with _git flow_.
