### ISSUE TITLE
How to add new types to changelog

### ISSUE THREAD

**Issue by ddennis** [conventional-changelog/conventional-changelog#155]
Hi - i have been using conventional-changelog for about a 6 months and it's great.
I am alittle confused about the documentation and how to add new types.

I would like to add a new type which goes into my changelog, like **feat** and **fix**.
If possible i would like to use **design** and **animation** if a commit has change the design or animation of the project and have that printed into the changelog?

I am using conventional-changelog with gulp and would assume i need to put a config object into the ***conventional-changelog-writer*** but i have no idea on what to put in.

```

   gulp.task('changelog', function () {
       return gulp.src('CHANGELOG.md', {
           buffer: false
       })
           .pipe(conventionalChangelog(
                 {
                       preset:'angular',
                    releaseCount:0
              }, {
                    // context goes here
              }, {
                    // git-raw-commits options go here
              }, {
                    // conventional-commits-parser options go here
              }, {
                    // conventional-changelog-writer options go here
              }

        ))
           .pipe(gulp.dest('./'));
   });
```

Any help would be much appriciated or an example.
Thanks Dennis

**Comment by stevemao** [comment]
An easier way to https://github.com/conventional-changelog/conventional-changelog/pull/146, please have a look at those projects and comment :)
Also https://github.com/conventional-changelog/conventional-changelog-writer/issues/20 would be make this easier
Currently you have to require the preset module, modify it and export as a new config object. Then you could use https://github.com/conventional-changelog/conventional-changelog-core#config
Does it make sense?

**Comment by ddennis** [comment]
Thank you for answering. 

I will look into how i can modify the preset config module.
I am closing this and I will reopen if needed. 

If ever you have the time, adding some basic examples to the different repos - would be very helpfull.

Thanks again

**Comment by ddennis** [comment]
**This is just for reference.**

The easiest (very dirty) solution was to fork the angular preset and modify it.
[solution here ](https://github.com/ddennis/conventional-changelog-ddennisl)

But it [ would have been easier if i could pass in an options object to the preset, instead of using a string to require the preset ](https://github.com/conventional-changelog/conventional-changelog/blob/master/index.js#L9) , this would also make it possible to pass in my own module, instead of always require node_modules. 

Like `conventionalChangelog({preset:require('my-preset')( myOptions ) }`

I haven't understood everything this modules tries to solve and I do apologize if there is a 1000 obvious reasons to way this is a bad idea - if so just ignore this and close it.

**Comment by stevemao** [comment]
There is a config object for you to do this. Again it's still not ideal yet. If you want to resolve this issue quickly please comment on the issues I have linked.

**Comment by renestalder** [comment]
Is there more information about how to create own "presets" with types? Somehow, I turn in circles if I follow links in this thread or try to understand how `config` works (can't find an example).

**Comment by Lirianna** [comment]
> Is there more information about how to create own "presets" with types? Somehow, I turn in circles if I follow links in this thread or try to understand how `config` works (can't find an example).

@renestalder You can use ddennis forked project as an example: https://github.com/ddennis/conventional-changelog-ddennis (he has added two new types). Hope this helps :simple_smile:
