### ISSUE TITLE
extract core logic from conventional-github-releaser to make it not github specific

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#162]
So that conventional-gitlab-releaser or similar can use it.

see: https://github.com/conventional-changelog-archived-repos/meta/issues/5

**Comment by hbetts** [comment]
Closing this issue out.

I recently deployed a mono-repository containing `conventional-github-releaser` and `conventional-gitlab-releaser` so that it will be easier for us to create a core package to support both platform-specific packages.

https://github.com/conventional-changelog/releaser-tools
