### ISSUE TITLE
look into transferring grunt-conventional-changelog to organization

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#163]
we should ask @btford if he wants to transfer https://github.com/btford/grunt-conventional-changelog to the conventional-changelog organization.

**Comment by stevemao** [comment]
He already agreed in https://github.com/btford/grunt-conventional-changelog/issues/62 but hasn't done it yet.

**Comment by btford** [comment]
<img width="588" alt="screen shot 2017-03-06 at 2 00 28 pm" src="https://cloud.githubusercontent.com/assets/474988/23632043/4ddae2e4-0275-11e7-9e25-46e7ed185770.png">

Sorry. I receive a tremendous amount of email, and just got to this now.

I attempted to transfer ownership, but apparently I do not have permission to. Happy to try again once this is resolved.

**Comment by stevemao** [comment]
@btford I have invited you as an owner. Would you like to try again?

**Comment by stevemao** [comment]
@btford You should be able to transfer now since your an admin. Thanks!

**Comment by hbetts** [comment]
Closing this out.

@btford please feel free to move package into the organization when you have a moment.
