### ISSUE TITLE
add a files stanza to each package.json, to reduce package size

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#165]
we should make sure there's an appropriate `files` stanza added to each `package.json` to reduce repo size.

see: https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/22

**Comment by thejameskyle** [comment]
Done in https://github.com/conventional-changelog/conventional-changelog/pull/211

**Comment by bcoe** [comment]
@thejameskyle thanks 👍 really appreciate your help on this project.
