### ISSUE TITLE
make conventional-changelog play nicely with lerna

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#168]
## Goal

I would like to make conventional-changelog work as elegantly with lerna as the [standard-version](https://github.com/conventional-changelog/standard-version#standard-version) workflow on singular repos.

### In Independent Mode

* It would be nice if logic similar to [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-recommended-bump) recommended version updates (rather than manual prompting).
* It would be nice to have a pretty CHANGELOG auto-generated for each module in `./package`.

### In Regular Mode

* It would be nice to have a pretty CHANGELOG auto-generated for each module in `./package`.

## Work To Do

- [x] scope `git log` to specific directory, so changes can be fetched for specific packages: https://github.com/conventional-changelog/conventional-changelog/pull/167
- [x] add support for lerna-format semver tags: https://github.com/conventional-changelog/conventional-changelog/pull/161
- [x] figure out an approach for hooking `conventional-changelog` into the lerna tagging process: https://github.com/lerna/lerna/issues/643
- [x] add support to conventional-changelog-core for lerna style commit tags (`pkg-name@version`).

CC: @hzoo, @Tapppi, @stevemao

**Comment by Tapppi** [comment]
#167 and #161 should be a-ok to go, @bcoe has been doing awesome progress.

**Comment by evocateur** [comment]
Oh geez, I would love to start re-using some of these packages (`git-semver-tags`, maybe more?) internally in `lerna`...

**Comment by nicojs** [comment]
Cool! This couldn't come at a better time for us as we're migrating to lerna as we speak and already use the awesome conventional-changelog. 

When will this be released?

**Comment by bcoe** [comment]
@nicojs would love the help testing; you can try things out by installing the canary build of lerna:

`npm i lerna@canary`.

**Comment by nicojs** [comment]
@bcoe i will definitely do that later today. How does it work? We just run `grunt conventionalChangelog` using a `lerna run` job?

**Comment by bcoe** [comment]
I'll document upstream, and perhaps write a bit of a post; currently it's
only enabled for independent mode (would love your thoughts on regular
mode, if this is what you're using) but! in independent mode you simply run:

lerna publish --conventional-commits

**Comment by nicojs** [comment]
Cool! How can i test it without doing an actual npm release? Or just use a different npm-tag?

**Comment by wizardzloy** [comment]
@nicojs 
```sh
lerna publish --skip-npm --conventional-commits
```
should do the trick

**Comment by wizardzloy** [comment]
@bcoe This are the awesome news. Let me know if you need some help with testing or implementing anything related to this functionality. We already are using `lerna-semantic-release` on our project, but we had some issues with making the CHANGELOG generation process working. I've done a smoke test with `lerna publish --conventional-commits` and looks like it works like a charm, would be happy to migrate to the "native" lerna + conventional-*** approach

**Comment by nicojs** [comment]
Thanks! I've created issue lerna/lerna#702 to follow up

**Comment by KingScooty** [comment]
So does `lerna publish --convertional-commits` work for fixed mode or only independent mode? I'd really like to still generate a changelog despite the fact i'm using fixed mode versioning. Is this possible?
