### ISSUE TITLE
Conventional-changelog not working if current version is the same as the last tag

### ISSUE THREAD

**Issue by waitingduck** [conventional-changelog/conventional-changelog#170]
Recently I ran into a problem that conventional-changelog(gulp-conventional-changelog) generate a blank changelog without any error.

After some investigation, I found that conventional-changelog is not going to work if the current version is the same as the last tag. 

So my current solution is to update the version then run the conventional-changelog.

I know it is not normal case because usually we will have everything done then push a new tag. This case only happened when someone like me, adopt conventional-changelog in the middle of project and happen to have the same version with last tag. Maybe it is better to have this specified in the doc or have a option to force generateing changelog?

Thanks

**Comment by stevemao** [comment]
Have you tried to set `outputUnreleased` to true?

**Comment by waitingduck** [comment]
Just tried and it works!

`gulp.task('changelog', function () {
  return gulp.src('CHANGELOG.md')
    .pipe(plugins.conventionalChangelog({
      // conventional-changelog options go here
      preset: 'angular',
      outputUnreleased: true
    }, {
      // context goes here
    }, {
      // git-raw-commits options go here
    }, {
      // conventional-commits-parser options go here
    }, {
      // conventional-changelog-writer options go here
    }))
    .pipe(gulp.dest('./'));
});`

And I just saw this in the doc. Thanks!
