### ISSUE TITLE
No output on `stdout` on linux

### ISSUE THREAD

**Issue by thuba** [conventional-changelog/conventional-changelog#182]
When using `conventional-changelog-cli`, changelog is correctly generated, but when using `conventional-changelog` nothing is printed to `stdout`. 

In `conventional-changelog-writter`, I can see that it correctly returns a transform stream.

- doesn't works on linux (tested on gentoo and archlinux) with node 6.4.5 and 7.8.0
- works on Mac OS 10.12.4 with node 6.4.5

Tested with this line of code:

~~~.js
var conventionalChangelog = require('conventional-changelog');

conventionalChangelog({ preset: 'angular'}).pipe(process.stdout);
~~~

Any idea ?

**Comment by stevemao** [comment]
The code doesn't look wrong to me. Could you provide a minimal repo that can replicate the problem? Maybe there's no changelog needs to be generated (try with debug or `outputUnreleased`)?

**Comment by thuba** [comment]
Ok, my bad, works perfectly finaly. Still have stranges behaviours but I think I need to search in my custom config preset. Thx!
