### ISSUE TITLE
link Name

### ISSUE THREAD

**Issue by jimblue** [conventional-changelog/conventional-changelog#186]
Hi,

It's more a question than an issue.
I'm using CLI and in the top of my changelog.md I've got this:

`<a name=""></a>`

What is it for? Is it possible to not write this line?

Thanks

**Comment by stevemao** [comment]
It's probably for the old markdown parser for an anchor link. I'm happy to remove it.

**Comment by jmbelloteau** [comment]
Great looking a new version then 😄 !

thank you

**Comment by eventualbuddha** [comment]
Not sure whether this is the same issue, but I'm seeing a broken `<a>` tag:

<img width="532" alt="screen shot 2017-05-16 at 5 51 13 am" src="https://cloud.githubusercontent.com/assets/1938/26106762/d1d831ec-39fb-11e7-9891-12f1690ee4af.png">

HTML for that release (before I fixed it):

```html
<a name"2.54.2"></a>
### 2.54.2 (2017-05-02)


#### Bug Fixes

* always replace the extension with .js (#1008) ([540ad1c1](https://github.com/decaffeinate/decaffeinate/commit/540ad1c1), closes [#1007](https://github.com/decaffeinate/decaffeinate/issues/1007))
```

Note the missing `=` between `<a name` and `"2.54.2"`.

**Comment by stevemao** [comment]
@eventualbuddha what version are you using?

**Comment by eventualbuddha** [comment]
Looks like 0.0.17:

```
├─┬ semantic-release@6.3.6
│ ├─┬ @semantic-release/commit-analyzer@2.0.0
│ │ └─┬ conventional-changelog@0.0.17
```

Which I see [is over two years old](https://github.com/conventional-changelog/conventional-changelog/tree/v0.0.17). I guess I'm stuck with this since `@semantic-release/commit-analyzer` [still depends on 0.0.17 today](https://github.com/semantic-release/commit-analyzer/blob/1821a51841329a468f85f7077f6ceed62ec57cf5/package.json#L17). 😢

**Comment by eventualbuddha** [comment]
Looks like fixing https://github.com/semantic-release/commit-analyzer/issues/15 would fix it for me, but I don't have much hope of that since that was filed in January 2017.

**Comment by luftywiranda13** [comment]
cc @boennemann @christophwitzko..
looks like many things in semantic-release are not in active development anymore 😢

**Comment by jmbelloteau** [comment]
I still got the same issue, the begining of my generated chagenelog look like this:

```md
<a name=""></a>
#  (2017-05-16)

* Add Cache Busting ([b617e61](https://gitlab.com/jmbelloteau/jmbelloteau/commit/b617e61))
```

Just update all my package, I'm now running with "conventional-changelog-cli v1.3.1"

I run it trough npm with this command in package.json :

"scripts": {
    "changelog": "conventional-changelog -i CHANGELOG.md -s -r 0"
  },
`

**Comment by jmbelloteau** [comment]
@stevemao @eventualbuddha @luftywiranda13 any idea?

**Comment by hbetts** [comment]
It would also need to be changed in every preset, such as the [angular](https://github.com/conventional-changelog/conventional-changelog/blob/1cc079df803f58b52c8aa997fff43e9c162266e7/packages/conventional-changelog-angular/templates/header.hbs#L1) preset.

**Comment by eventualbuddha** [comment]
My separate-but-related bug was fixed, so I’m going to bow out of this conversation. Thanks!

**Comment by hbetts** [comment]
Successfully published:
 - conventional-changelog-angular@3.0.3
 - conventional-changelog-atom@0.2.6
 - conventional-changelog-cli@1.3.18
 - conventional-changelog-codemirror@0.3.6
 - conventional-changelog-core@2.0.7
 - conventional-changelog-ember@0.3.8
 - conventional-changelog-eslint@1.0.7
 - conventional-changelog-jquery@1.3.6
 - conventional-changelog-jshint@0.3.6
 - conventional-changelog-writer@3.0.6
 - conventional-changelog@1.1.20
 - gulp-conventional-changelog@1.1.20
 - standard-changelog@1.0.15
