### ISSUE TITLE
Filter out tests in published tests

### ISSUE THREAD

**Issue by hzoo** [conventional-changelog/conventional-changelog#191]
Can we get a new published version with the `tests` folder removed from the published output? Either with npmignore or "files"?

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-core

https://github.com/facebook/flow/issues/1420#issuecomment-259150408
https://travis-ci.org/babel/babel/jobs/236669417

Ironically I believe I'm seeing this in Babel after updating lerna which uses conventional-changelog in the deps (which it it's is using)

**Comment by stevemao** [comment]
See https://github.com/conventional-changelog/conventional-changelog/issues/165
Also could you answer https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/22#issuecomment-270778816? Thanks :)
