### ISSUE TITLE
Do not publish tests and malformed JSON files to npm.

### ISSUE THREAD

**Issue by cpojer** [conventional-changelog/conventional-changelog#197]
Currently the `test/fixtures/_malformation.json` file is part of the published code to npm. Flow is picking this file up and reports an error, requiring us to blacklist this file. Would you mind tuning the settings for this repository to exclude test files from being published to npm?

**Comment by stevemao** [comment]
See https://github.com/conventional-changelog/conventional-changelog/issues/165
Also could you answer https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/22#issuecomment-270778816? Thanks :)
