### ISSUE TITLE
Support multiple types and scopes

### ISSUE THREAD

**Issue by AndersDJohnson** [conventional-changelog/conventional-changelog#202]
Sometimes a commit is of multiple types or affects multiple scopes. E.g. updating tests or docs along with code change. We might want to think about how to support multiple types and scopes.

**Comment by stevemao** [comment]
This means you might have duplicates under an entry. EG:

```md
### Features

* **breakingChanges:** make BREAKING CHANGE more forgiving ([7dce559](https://github.com/conventional-changelog/conventional-changelog-angular/commit/7dce559))


### Bug Fixes

* **noteKeywords:** make BREAKING CHANGE more forgiving ([7dce559](https://github.com/conventional-changelog/conventional-changelog-angular/commit/7dce559))
```

Should you just make it two commits in the first place?

**Comment by AndersDJohnson** [comment]
@stevemao Sometimes people have precommit hooks that require tests to pass. So a fix or feature is going to include tests. Are we saying that `test` type is only for commits that include only tests?

**Comment by stevemao** [comment]
I do sometimes write commits like

```
fix(client,server): integration
```

And it will become

```
### Bug Fixes

* **client,server:** integration ([7dce559](https://github.com/conventional-changelog/conventional-changelog-angular/commit/7dce559))
```

`client,server` doesn't group with other entries. In that case we already support multiple scopes

**Comment by stevemao** [comment]
> Sometimes people have precommit hooks that require tests to pass. So a fix or feature is going to include tests.

In that case it should be just fix or feature. 

> Are we saying that test type is only for commits that include only tests

yes only occasional missing tests or when you want to increase your coverage.
