### ISSUE TITLE
Proposal: lint commit messages via hook and CI

### ISSUE THREAD

**Issue by marionebl** [conventional-changelog/conventional-changelog#210]
I propose the addition of `commitlint` to the project tooling to check commit messages against a ruleset via husky and the CLI. 

The rules could include dynamic scopes based on lerna packages present in the mono repo plus some defined static scopes. See [@commitlint/config-lerna-scopes](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-lerna-scopes)

 Is this something you'd be interested in?

**Comment by stevemao** [comment]
On GitHub we fix the commit message and squash on merge via the GUI. On hosts like Gitlab, there's no easy way to do it via the GUI so I think it would be useful. 
CC @bcoe

**Comment by marionebl** [comment]
@stevemao To clarify I meant to add tooling for this repository, no additional package to be developed inside here.

**Comment by stevemao** [comment]
> To clarify I meant to add tooling for this repository,

Yeah I meant this project is hosted on GitHub, so we actually fix the commit on merge. I asked you to change the message because you needed to amend the commit anyway :)

**Comment by marionebl** [comment]
Ok, understood. I reckon we can close this proposal then.

**Comment by stevemao** [comment]
@marionebl Thanks for the proposal! We can reopen if necessary :)
