### ISSUE TITLE
Estimated release of latest changes

### ISSUE THREAD

**Issue by dlmr** [conventional-changelog/conventional-changelog#220]
Hi!

Sorry for creating this issue but I'm curious if there is a timetable for when the latest changes to master will be released, specifically for `conventional-changelog-angular`.

I would like to prevent creating a fork but if the release might be some time away I will need to do it in the meantime.

Thanks for maintaining this project and tell me if there is something I can help with to make the release possible.

**Comment by stevemao** [comment]
I'm really sorry. It's published now :)

**Comment by dlmr** [comment]
Thanks! 🎉
