### ISSUE TITLE
[Angular] Support for `refactor` in conventional-changelog-angular

### ISSUE THREAD

**Issue by shsu** [conventional-changelog/conventional-changelog#222]
Looking at recent changelogs from angular, they have a dedicated section for `refactor` changes. 

https://github.com/angular/angular/blob/master/CHANGELOG.md#code-refactoring-2

**Comment by stevemao** [comment]
See https://github.com/conventional-changelog/standard-version/pull/195

**Comment by shsu** [comment]
Alright, I thought `changelog-angular` follows the `angular` project closely.

**Comment by stevemao** [comment]
They didn't include it before. I wonder if it's before they have a breaking change in those commit.
