### ISSUE TITLE
BUG: Using a Custom Preset Config Not Working With `conventional-changelog-cli`

### ISSUE THREAD

**Issue by stalinkay** [conventional-changelog/conventional-changelog#227]
# Problem

@stevemao I created a custom preset by forking the conventional-changelog-angular. It can get it produce the expected output by dropping it into `/usr/local/lib/node_modules/conventional-changelog-cli/node_modules`. It is, however, not working with the --config option of the CLI, which is my preferred way of using it. It simply outputs the changelog without any expected sections, e.g. Added, Removed, etc.

# Steps to reproduce
 
1. Install the preset in an existing project with a few commits `npm install --save-dev conventional-changelog-stalinkay`
 2. Use `conventional-changelog --config ./node_modules/conventional-changelog-stalinkay/index.js -r 0`

# Expected Behavior

I expect changelog to contain the custom sections when using a custom --config but none are present when using the steps above.

**Comment by RayBenefield** [comment]
I just noticed this last night and found a quick fix that will work for this. Putting in a pull request in a bit. It is a one line fix.

**Comment by stalinkay** [comment]
@RayBenefield 💯. Thanks.
