### ISSUE TITLE
Types can't have dashes

### ISSUE THREAD

**Issue by paulirish** [conventional-changelog/conventional-changelog#234]
The header pattern here: 
https://github.com/conventional-changelog/conventional-changelog/blob/09b1a0a57bcee4628b4c0b20920079d055f34a70/packages/conventional-commits-parser/index.js#L9

...doesn't allow for a type of `new-feature`, but seemingly otherwise things would have worked.

Not a huge deal but if you'd prefer dashes not be allowed in types, then perhaps an error should be thrown? alternatively, update the regex. 

downstream: https://github.com/GoogleChrome/lighthouse/pull/3534

**Comment by stevemao** [comment]
Oh, type is supposed to be one word. dashes are used to separate words.

throwing an error/warning when there is no math to the header sounds reasonable. 

Side: there might be other places we can warn/throw when configured wrong to be more friendly.

**Comment by marionebl** [comment]
You may want to pass a `headerPattern` that matches your requirements. How that works depends on the `conventional-changelog` tool you use. 

I can't find the command you use to generated the Lighthouse [changelog](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md). Could you provide it?

**Comment by stevemao** [comment]
@marionebl `new-audit` is not a valid types because it's not a single word. I believe they just want to use sensible defaults. 
Point is it'd be really good we could print better error/warning in general 😄

**Comment by hbetts** [comment]
Then should this issue be closed out, and a new issue filed to reflect the need for better warnings and errors?

**Comment by stevemao** [comment]
@hbetts sounds good.

**Comment by hbetts** [comment]
Closing in favor of #261

**Comment by Jack-Barry** [comment]
If anyone else hits this, I'm using the following to get this to play nice with the output from `cz-emoji` with the `conventional` flag set to `true`:

`commitlint.config.js`

```js
const commitTypes = require('cz-emoji/lib/types.json')

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', commitTypes.map((type) => type.name)],
  },
  parserPreset: {
    parserOpts: {
      headerPattern: /^((?:\w|-)*)(?:\((.*)\))?!?: (.*)$/,
      breakingHeaderPattern: /^((?:\w|-)*)(?:\((.*)\))?!: (.*)$/,
    },
  },
}
```

The trick is changing the first capture group in the regex from `(\w*)` (as found in [`parser-opts.js`](https://github.com/conventional-changelog/conventional-changelog/blob/d9feeb605de28c00ef55b5c8e229efd1289dd6e8/packages/conventional-changelog-conventionalcommits/parser-opts.js#L6-L7)) to `((?:\w|-)*)`

This approach could be stupid, I'm not sure. But it works 🤷
