### ISSUE TITLE
conventional-changelog-cli: Override dateformat

### ISSUE THREAD

**Issue by wardpeet** [conventional-changelog/conventional-changelog#243]
So I started using the cli and want my preset to order by committer date. The problem is that conventional-changelog-core formats the date by default to yyyy-mm-dd and it's not overwritable by the cli. My idea is just to add time to the format by default.

I need the correct date format to sort by committerDate which now doesn't make much sense if you have multiple commits on the same day.

Is there a reason why you strip out the time?

**Comment by stevemao** [comment]
You should be able to overwrite it 
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#date

**Comment by hbetts** [comment]
@stevemao I think the issue is that the CLI doesn't allow you to override that value in the `writer`.

**Comment by stevemao** [comment]
@hbetts A more generic solution would be https://github.com/conventional-changelog/conventional-changelog/issues/195

**Comment by wardpeet** [comment]
it looks like @stevemao is all I needed afterall :) so feel free to close this
