### ISSUE TITLE
Stop recommending validate-commit-msg

### ISSUE THREAD

**Issue by danielo515** [conventional-changelog/conventional-changelog#246]
The project seems to be deprecated:

> DEPRECATED. Use https://github.com/marionebl/commitlint instead. githook to validate commit messages are up to standard http://conventionalcommits.org/

I'm currently using [npm](https://www.npmjs.com/package/validate-commit) [github](https://github.com/willsoto/validate-commit) which works out of the box without changing anything, just installing it.

Regards

**Comment by stevemao** [comment]
PR welcome :)

**Comment by hbetts** [comment]
As noted by @stevemao a pull request would be really appreciated!

**Comment by danielo515** [comment]
Hello @stevemao , why do you think commitilint is better ? Seems more configurable, but also more hard to configure. What about recommending both ?

Regards

**Comment by hbetts** [comment]
@danielo515 it may be for the simple reason that `validate-commit` doesn't use `conventional-changelog`.

So `commitlint` will share the same preset behaviors as other packages in the `conventional-changelog` ecosystem, while `validate-commit` may express slightly different behaviors.

**Comment by danielo515** [comment]
@hbetts thanks for the clarification, that makes sense.
