### ISSUE TITLE
Only for node.js?

### ISSUE THREAD

**Issue by sirvon** [conventional-changelog/conventional-changelog#250]
I keep seeing the docs mentioning package.json.

Do these instructions/lib only apply to node projects, 
can this work with swift, ios, android etc,etc projects?

Aslong as there is a git commit record, correct?

my first go around in running this command
```bash
$ conventional-changelog -p angular -i CHANGELOG.md -s -r 0
```
in directories that held ios, android, and html/js projects only produced a file,
that had this...
```markdown
<a name=""></a>
#  (2017-11-19)

```

**Comment by stevemao** [comment]
What do your commit messages look like?

**Comment by hbetts** [comment]
@sirvon, as hinted at by @stevemao, `conventional-changelog`, along with higher level packages like `standard-version` and `standard-changelog`, support other languages (though you will need a `package.json` file so that `conventional-changelog` can extract the repository URL).

**Comment by sirvon** [comment]
is there a generator command for the cli or just create one by hand?

**Comment by stevemao** [comment]
You can use [commitizen](https://github.com/commitizen/cz-cli) to generate your commit messages :)
