### ISSUE TITLE
Alternate changelog links for gitlab?

### ISSUE THREAD

**Issue by flyinbutrs** [conventional-changelog/conventional-changelog#257]
The compiled markdown file puts links to the commits in the changelog as:

````{{repo_url}}/commits/{{commit_hash}}````

However, gitlab uses: 

````{{repo_url}}/commit/{{commit_hash}}````

 Is there any ability to modify this?

**Comment by stevemao** [comment]
Is your host set to gitlab? https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-core/hosts/gitlab.json

**Comment by flyinbutrs** [comment]
No, how do I do that? I don't see it in the documentation anywhere.

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#host

**Comment by flyinbutrs** [comment]
Yeah, I found that in the docs, but I don't quite understand how to change that parameter. I assume by the docs there that it will default to the hostname of your repo, but in my case it's a private hosted gitlab, so it can't determine it from that hostname. Should I just add ```"host": "gitlab"``` to my ```package.json```?

**Comment by flyinbutrs** [comment]
Figured it out...  

in case anyone googles and is looking for the answer:

```"repository": "gitlab:<repo_url_here>"```

**Comment by flyinbutrs** [comment]
Actually, strike that...  I just noticed, when you do ```gitlab:<url>```, it assumes you want gitlab.com, and prefixes your repo URL with ```https://www.gitlab.com/```. Is there any way to use gitlab style issues/commit links but with a privately hosted gitlab?

**Comment by stevemao** [comment]
For now, you could overwrite any context value. 

```js
conventionalChangelogCore(options, {
    host: 'gitlab'
})
```

**Comment by flyinbutrs** [comment]
Interesting. I'm trying to use standard-version / commitizen / standard-changelog with a variety of non-NPM packages (python, ruby, puppet), because I find it much friendlier out of the box than the other tools I've used for this type of build activity. 

That being said, I'm not really NPM "aware" in terms of what might be conventional in the JS world, and the docs are not really friendly to my use case (possibly for a reason). 

So...  where would I put that? Is there a guide I'm missing for how to "configure" this suite and where to put tweaks like this?

**Comment by hbetts** [comment]
@flyinbutrs the sue of `standard-version` and `commitizen` is fine, and, by download count, used quite extensively within the JavaScript community.

I believe `standard-changelog` is just `conventional-changelog`, but setup to use the `angular` preset by default.

@flyinbutrs can you re-post this issue on the `standard-version` project?

I believe the issue will be that `standard-version` does not allow you to forward options like `host` to the underlying `conventional-changelog` library.

Long-term I believe the goal is to allow configuration through an RC file at the root of a project - #195

**Comment by flyinbutrs** [comment]
@hbetts I will repost there. I think this can also be fixed to allow package.json's .repository.type to be allowed in cases where autodetection fails pretty easily. I laid out the steps in [this PR](https://github.com/conventional-changelog/conventional-changelog/pull/258).

**Comment by muuvmuuv** [comment]
I do have the same issue with a self-hosted version of GitLab, see my issue #616. IMO the best solution is a custom config (#195) for this to exactly specify the host to `gitlab` and a `repoUrl` to separate it. Fallback to package.json is still an option then.

**Comment by baby-gnu** [comment]
As I had the same issue using `semantic-release`, I [override 3 url format option](https://github.com/semantic-release/release-notes-generator/issues/449#issuecomment-1569889772) as [described in the documentation](https://github.com/conventional-changelog/standard-version/blob/4fcd4a7edabbfe4183fbaa7fcd0f55b2441449d1/README.md#customizing-changelog-generation)
