### ISSUE TITLE
Standard Lockfile

### ISSUE THREAD

**Issue by hbetts** [conventional-changelog/conventional-changelog#269]
I was wondering if the `conventional-changelog` core team had a preference for a lockfile format?

If the package manager of choice is `npm`, then is it alright to start submitting `package-lock.json` lockfiles to the repository?

(The alternative is to switch to Yarn and use `yarn.lock` lockfiles)

**Comment by stevemao** [comment]
From what I can see many tools/libs are ignoring lockfiles now. Lockfiles are good for projects not libs I guess?

**Comment by hbetts** [comment]
I'm not sure what you mean by `projects`, but let's consider `conventional-recommended-bump` (since I'm working on that project now).

If I were to globally install `conventional-recommended-bump` with the intention of using its CLI interface, `npm` and `yarn` would install all dependencies, and transitive dependencies, based on what is available at installation time from the npm registry.

Therefore, even if you install the same version of `conventional-recommended-bump`, you are not guaranteed to get the same set of dependencies.

So a lockfile would provide some guarantee for CLI users of `conventional-changelog` tools.

With respect to pure libraries, I still advocate for lockfiles. Lockfiles aren't just for runtime dependencies. They're also great for development dependencies.

Lockfiles are a great way to ensure that contributors to a library can pull down the project, add their contribution, and submit a pull request, all while using a know set of working development dependencies. For example, all my personal projects are setup with lockfiles. The last thing I want is for someone to say they tried to submit a pull request, but gave up because some unrelated development, or transitive, dependency broke.

**Comment by hbetts** [comment]
I'll put up a pull request with `package-lock.json` files from `npm` version 5 to see what interest there is in adopting it.
