### ISSUE TITLE
No matching version found

### ISSUE THREAD

**Issue by alexw10** [conventional-changelog/conventional-changelog#283]
I am getting issue with build with this package now.

Here is the error:
npm ERR! notarget No matching version found for conventional-changelog-angular@^1.6.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'conventional-changelog'
npm ERR! notarget 

Any ideas?

**Comment by zackarychapple** [comment]
Most likely hitting this. https://github.com/conventional-changelog/conventional-changelog/issues/279

**Comment by Tapppi** [comment]
Duplicate
