### ISSUE TITLE
README.md link to "popular projects" presets doesn't work

### ISSUE THREAD

**Issue by c0bra** [conventional-changelog/conventional-changelog#285]
Here: https://github.com/ajoslin/conventional-changelog#preset

There is no anchor for preset

**Comment by stevemao** [comment]
the link should be https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog#preset
PR welcome :)

**Comment by hbetts** [comment]
Thanks to the work of @TheDancingCode we have successfully published the following package documentation fixes:
 - conventional-changelog-cli@1.3.20
