### ISSUE TITLE
Recommend different bumping strategy for 0.x versions

### ISSUE THREAD

**Issue by bajtos** [conventional-changelog/conventional-changelog#294]
Right now, conventional-recommended-bump does not distinguish between 0.x and post-1.0 versions when recommending the next version.

The current behaviour for 0.x versions:

 - Breaking changes bump semver-major version to `1.0.0`. This is almost never wanted!
 - Features bump semver-minor version (`0.<x>.0`). This does not work with npm's carrot (`^`) operator.
 - Patches bump semver-patch version (`0.x.<y>`).

I am proposing to implement a different behavior for 0.x versions:

 - Breaking changes bump semver-minor version (`0.<x>.0`).
 - All backwards-compatible changes (features and patches) bump semver-patch version (`0.x.<y>`).

This allows consumers of modules to specify the dependency version as `^0.x.y` to receive all backwards-compatible updates.

See https://www.npmjs.com/package/semver#caret-ranges-123-025-004:

> **Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4**
> (...) this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

**Comment by bajtos** [comment]
If we agree this change is welcome, then I am happy to contribute a pull request myself. However, it would great if the licensing issue https://github.com/conventional-changelog/conventional-changelog/issues/286 could be sorted out first!

**Comment by hbetts** [comment]
@bajtos there was a similar issue filed several months ago - #239 

`conventional-recommended-bump` simply determines what type of change was made (`major`, `minor`, `patch`) and defers to the downstream user as to what version number is generated from that release type.

**Comment by bajtos** [comment]
@hbetts thank you for a quick response. I read through the discussion in #239 and https://github.com/npm/node-semver/issues/177. The reasoning make sense, I am closing this issue as a duplicate and/or invalid.
