### ISSUE TITLE
About subprojects

### ISSUE THREAD

**Issue by vxhly** [conventional-changelog/conventional-changelog#297]
Hello！
My main project is called shop and subproject is called shop-app.
When I run git cz under the subproject shop-app,
The commit url in the created CHANGLOG.md points to the main project but not the subproject.

I expect is :https://gitlab.com/qianqu/shop/shop-app/commit/6cba4ee)
But it became: https://gitlab.com/qianqu/shop/commit/6cba4ee)

The a-tag generated at the head of the file is also what I don't want.

what should I do？

**Comment by hbetts** [comment]
@vxhly were you able to determine why the URL was incorrect?

**Comment by vxhly** [comment]
sorry! I already know where the problem is.  
I only need to add in package.json
```bash
  "repository": {
    "type": "git",
    "url": "git+ssh://"
  },
```
