### ISSUE TITLE
ESLint preset, changelog shorten commit id

### ISSUE THREAD

**Issue by unlight** [conventional-changelog/conventional-changelog#313]
Currently eslint changelog is generated like:
```
* First release ([dba029508705fc452289413b63f6431f652d1cbc](https://github.com/unlight/jest-createspyobj/commit/dba029508705fc452289413b63f6431f652d1cbc))
```

Link to commit is too long, is it possible to add option to generate 7-symbol commit link like github `[dba0295](full-link)`

**Comment by bravo-kernel** [comment]
I am experiencing the same. Browsing through the issues I think there might be two possible solutions. If somebody can confirm or advise I am willing to PR, much appreciated 👍.

- implementing a custom `writerOpts.transform`
- implementing a custom handlebars template
