### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by RobLoach** [conventional-changelog/conventional-changelog#326]
Conventional Changelog currently doesn't have a changelog. It would be great to add one.

**Comment by damianopetrungaro** [comment]
LOL

**Comment by damianopetrungaro** [comment]
@RobLoach are you free to work on it?

PR is welcome 😄

**Comment by crutchcorn** [comment]
The IRONY - it PAINS me

**Comment by hbetts** [comment]
Changelogs for `conventional-changelog` packages are under their respective package directories within the mono-repository.

For example, the changelog for `conventional-changelog-core` is available here - https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-core/CHANGELOG.md
