### ISSUE TITLE
[conventional-changelog-cli] option "tagPrefix" is not supported

### ISSUE THREAD

**Issue by PixelJonas** [conventional-changelog/conventional-changelog#337]
Currently I'm running a [nx-workspace](https://nrwl.io/nx) hosting multiple libraries with example apps. Each library is versioned/released seperatly. 
I really like to generate the changelogs for each library automaticly. Currently I use the `--commit-path` option which is working great. The only problem I'm facing right now is figuring out how to tag the commits for each library to `conventional-changelog` is able to generate the correct changelog.

Reading the `README.md` for [conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core) I found the option `--tagPrefix`. So I'm guessing I could tag the commits with a custom prefix like `--tagPrefix=mylib-v/0.0.1`.

Currently this seems not be supported by [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli). 

Did I miss anything? Otherwise I'd like to contribute this feature.

Best Regards,
PixelJonas

**Comment by hbetts** [comment]
> Reading the README.md for conventional-changelog-core I found the option --tagPrefix. So I'm guessing I could tag the commits with a custom prefix like --tagPrefix=mylib-v/0.0.1

You are correct. `tagPrefix` was intended to allow `conventional-changelog` to support mono-repositories that use custom tag prefixes to identify their libraries (as opposed to using the tag prefix standard with [LernaJS](https://lernajs.io/)).

> Currently this seems not be supported by conventional-changelog-cli.

That is correct. Support was added to `conventional-changelog-core` in pull request #300, but that support was never extended to `conventional-changelog-cli`.

> Otherwise I'd like to contribute this feature.

We'd definitely welcome the contribution! :+1:

**Comment by mrpaaske** [comment]
Hi! I'm trying to use this feature, but it doesn't seem to work as I expect :)

Running `conventional-changelog -p angular -t prefix-v` still gives me everything from whatever version is in the package.json (which **doesn't** have the prefix) and back **without** the prefix.

So if I have this git log
```
* commitid fix(www): hooray-3
| * commitid (HEAD) (tag: prefix-v1.2.2) fix(www): yay-2 <-- HEAD is here, package.json says 1.2.2
| * commitid (tag: prefix-v1.2.1) fix(www): yay-1
| * commitid (tag: prefix-v1.2.0) feat(www): yay-0
|/
* commitid (tag: v1.1.0) feat(www): hooray-2 <-- no prefix
* commitid feat(www): hooray-1
* commitid (tag: v1.0.0) feat(www): hooray-0 <-- no prefix
* commitid chore: initial commit
```

the changelog will show 

1.1.0 to 1.2.2
1.0.0 to 1.1.0

ignoring the prefixed tags.

I would expect it to show only prefixed tags:

1.2.1 to 1.2.2
1.2.0 to 1.2.1
everything from initial commit to 1.2.0

Any tips on how I'm supposed to do this?

**Comment by liufsd** [comment]
@mrpaaske  +1 ....
