### ISSUE TITLE
`getWriterOpts` of `/packages/conventional-changelog-angular/writer-opts.js` does not seems right

### ISSUE THREAD

**Issue by grubyak** [conventional-changelog/conventional-changelog#352]
every commit note gets `BREAKING CHANGES` title in https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/writer-opts.js#L31-L34 - is that expected?

also seems that there is no way to get changelog generator to render custom type (other than feat, fix, perf, revert, breaking change) and add to it changelog, or did i miss something?

**Comment by shrutimistry** [comment]
If your using `git cz` when commiting, you can check this out: 
https://github.com/leonardoanalista/cz-customizable/blob/master/cz-config-EXAMPLE.js 
It allows to add your own custom type and pass in this configfile to your package.json, then you can just reference this type in the writer-opts.js file.

**Comment by hutson** [comment]
@grubyak the `conventional-changelog-angular` preset package only recognizes a single note, those commits that are breaking changes. Therefore it treats all notes as breaking changes.

If you would like to use a different set of types, please consider creating a fork of the `conventional-changelog-angular` preset. That has been our general recommendation for customizing the behavior of Conventional Commits when you use types that are not part of the Angular commit convention.
