### ISSUE TITLE
How to change range of commit id?

### ISSUE THREAD

**Issue by dgroh** [conventional-changelog/conventional-changelog#358]
How can I get the whole git id instead of only one part of it in the URL (hover the link below to see the URL)?

* **map:** add [hammerjs](http://hammerjs.github.io/) ([3060772](https://myrepoaddress/commits/30607722028937482726485738637463))

**Comment by stevemao** [comment]
Use this option: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#transform
