### ISSUE TITLE
Lerna Repo, not recognising git tags / versions

### ISSUE THREAD

**Issue by ChrisSargent** [conventional-changelog/conventional-changelog#402]
See this minimal example repo: https://github.com/ChrisSargent/changelog-test

Attempting to generate a changelog from the initial commits with release count = 0.

Try running `yarn install` and then `yarn changes`. You'll see that the generated changelog puts all commits under the version from the package.json file.

Tried all manner of cli options, tried multiple `console.log()` and seems to have the correct array of git tags but couldn't get it to work. Wasn't sure how to write a failing test but I hope this minimal repo does enough to demonstrate the problem.

If this isn't a config option problem then I'm happy to help out with some PR but could do with some advice of where to start.

Thanks,

Chris

**Comment by MikeRalphson** [comment]
Seeing something similar, in my case may be related to the fact I've gone back to previous points in the history to do patch releases **after** the main latest release from the master branch.

**Comment by stevemao** [comment]
This repos only contains low level parser/writer for now. You can use https://github.com/conventional-changelog/standard-version for monorepo. Alternatively, you could read it's source code to learn how to config this repo to support monorepo.

**Comment by MikeRalphson** [comment]
Thanks @stevemao - will give that a try.

**Comment by ChrisSargent** [comment]
@stevemao - thanks for your reply but I don't really follow how this helps.

I tried installing 'standard-version' and using it to do a first generation of commits. However, it put all of my commits in to the same release in the changelog - exactly the same behaviour as detailed above.

In the lerna repo, they recommend using conventional changelog CLI for first generation of logs: https://github.com/lerna/lerna/issues/1361

I'm already using the `"conventionalCommits": true,` option in Lerna and it generates great logs for each release. But what I'm trying to achieve is to re-generate the changelog from scratch (because we updated our configs).

**Comment by stevemao** [comment]
> I'm already using the `"conventionalCommits": true,` option in Lerna and it generates great logs for each release when running `lerna release`. But what I'm trying to achieve is to re-generate the changelog from scratch (because we updated our configs).

This should work. Did you try `lerna version --conventional-commits`?

**Comment by stevemao** [comment]
Sorry. This does sound like a missing feature. I'm not sure if we should support lerna repos here in these low level modules. I'm not sure which wrapper should support it (I thought lerna did)... But I'm open to discuss.

**Comment by evocateur** [comment]
Lerna is just passing significant pieces of config to conventional-changelog APIs. You should be able to do the same with the `conventional-changelog` CLI and some judicious `lerna exec` from the root of your monorepo:

```bash
# Lerna does not actually use conventional-changelog-cli, so you need to install it temporarily
npm i -D conventional-changelog-cli

# fixed versioning (default)
# run in root, then leaves
npx conventional-changelog --preset angular --release-count 0 --outfile $PWD/CHANGELOG.md --verbose
npx lerna exec --concurrency 1 --stream -- 'conventional-changelog --preset angular --release-count 0 --commit-path $PWD --pkg $PWD/package.json --outfile $PWD/CHANGELOG.md --verbose'

# independent versioning
npx lerna exec --concurrency 1 --stream -- 'conventional-changelog --preset angular --release-count 0 --commit-path $PWD --pkg $PWD/package.json --outfile $PWD/CHANGELOG.md --verbose --lerna-package $LERNA_PACKAGE_NAME'
```

**Comment by stevemao** [comment]
Thanks @evocateur ! This is not very obvious IMO so we should add it to the docs :)

**Comment by swernerx** [comment]
I'm just wondering if this tip works for you guys so far. After running it, I see only one version with all changes in the new changelog. But my expectation was to get a real changelog where every version is listed with all changes. Wouldn't that be more correct?

**Comment by WaleedAli070** [comment]
Was wondering if we can have a glob pattern support for `tag-prefix`, that way we can support lerna packages too.  something like `--tag-prefix @root/{*}@` where `*` would match lerna package names. 
Or even, an array of prefixes would also do, e.g: `--tag-prefix [@root/package1@, @root/package2@]`.
