### ISSUE TITLE
Missing tag for ESLint convention

### ISSUE THREAD

**Issue by Berkmann18** [conventional-changelog/conventional-changelog#403]
The ESLint convention includes `Chore` which is what the ESLint team actively use, however it's not present on the [README](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint).

EDIT: I'll open a PR once, all the local tests pass.

**Comment by Berkmann18** [comment]
Also, not really related to this issue but wouldn't having `commitizen` set up with the angular convention (since that's what is used on this repo) be a good idea?
I noticed it wasn't set up after `git cz`ing when I finished my PR which was set to ESLint.

**Comment by stevemao** [comment]
Can you link where ESlint includes `Chore`? Also need to update https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint

**Comment by Berkmann18** [comment]
@stevemao [There you go](https://eslint.org/docs/developer-guide/contributing/pull-requests).
Okay, I'll update my PR with changes for that as well.

**Comment by Berkmann18** [comment]
@stevemao Wouldn't updating the changelog for that package also update the rest or am I missing something in [conventional-changelog-eslint](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint)?

**Comment by stevemao** [comment]
Sorry, What do you mean?

**Comment by Berkmann18** [comment]
@stevemao I mean, apart from updating `conventional-changelog-eslint` with that I did in #404, wouldn't it affect the whole repo instead of just that package?

**Comment by stevemao** [comment]
Each package is independent. But they are often used together so we put them in a monorepo. Easier to dev/test.

**Comment by stevemao** [comment]
There might be some other parts need to be updated too. EG:

```
Based on https://github.com/eslint/eslint.github.io/blob/master/docs/developer-guide/contributing.md#step-2-make-your-changes
```

The link needs to be updated. I'm fine with updating it in a separate PR though if you think it's a better idea.

**Comment by Berkmann18** [comment]
@stevemao Just saw your comment (not sure why it went in my read notifications).
I've updated my PR with a correct URL.
