### ISSUE TITLE
[Question] How to properly allow local development of the conventional-changelog?

### ISSUE THREAD

**Issue by adamchenwei** [conventional-changelog/conventional-changelog#406]
Specifically, I am trying to create my own version of the commit-parser to parse commit with some twist with conventional-changelog-cli. I forked the repo, but I am not sure how to proceed.
I wonder if there is a way allows me to develope a customized version of the parser and be able to test locallly. current I am thinking about to do the following:

add my fork of the monorepo as the dependency
then cli module able to load a custom parser module inside the repo
then I rebuild the monorepo (somehow)
then I (maybe) should be able to load the change by loading a different branch of the forked repo with git repo name and url.
see updated version of the conventional-changelog-cli work....

Or there is a better approach for local development of the conventional-changelog?

**Comment by stevemao** [comment]
Did you try start modifying the code in https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser?

**Comment by adamchenwei** [comment]
yes, I did. but I can't find a proper way to build the whole thing. since it suppose to be a dep in another testing repo https://github.com/adamchenwei/playground-channgelog-generator. git url does not work there if I want to just import cli... any suggestion?

**Comment by stevemao** [comment]
You don't need to build it. try symlinks? Or just publish it to npm with a different name.

**Comment by stevemao** [comment]
Since this question is general and not specific to conventional-changelog, try lerna/npm's forum or stackoverflow? They can probably give you much better answers.
