### ISSUE TITLE
add gitRawCommitsExecOpts parameter for conventional core

### ISSUE THREAD

**Issue by axetroy** [conventional-changelog/conventional-changelog#419]
the source code of `git-raw-commits`

There should be 2 parameters `rawGitOpts` and `rawExecOpts`.

```js
function gitRawCommits (rawGitOpts, rawExecOpts) {
  var readable = new stream.Readable()
  readable._read = function () {}

  var gitOpts = normalizeGitOpts(rawGitOpts)
  var execOpts = normalizeExecOpts(rawExecOpts)
  var args = getGitArgs(gitOpts)

  if (gitOpts.debug) {
    gitOpts.debug('Your git-log command is:\ngit ' + args.join(' '))
  }
```

But there is only one parameter here.

https://github.com/conventional-changelog/conventional-changelog/blob/97ad96fe893bd5b40ec52e24fe46f4f9cd357a1a/packages/conventional-changelog-core/index.js#L23-L28

here is an example to set base dir to parse the commit that is what I need

```js
gitRawCommits(gitRawCommitsOpts, { cwd: 'path/to/your/git/project' });
```

**Comment by stevemao** [comment]
I think we can add this. @axetroy PR welcome.

**Comment by axetroy** [comment]
@stevemao
it seem it will break the API

**Comment by stevemao** [comment]
If we put `rawExecOpts` as the last argument it won't. WDYT?

**Comment by axetroy** [comment]
Now current API requires 5 argument

```
conventionalChangelogCore([options, [context, [gitRawCommitsOpts, [parserOpts, [writerOpts]]]]])
```

If we add one more parameter, this should be a bad and terrible design.

that's why it breaks!

**Comment by stevemao** [comment]
True. I'm not sure how to add it. Ideas welcome :)

**Comment by axetroy** [comment]
Should be refactored to accept only one parameter.

extensible, no matter what parameters are added later

```javascript
conventionalChangelogCore([options]);
```

of course, this is up to you and your team, because it breaks the interface.

Sooner or later, it will become like this, just a matter of time.

**Comment by axetroy** [comment]
Or if you don't want to do a destructive update

Then merge parameters `gitRawCommitsOpts` and `rawExecOpts` into on object.

The current API remains unchanged.

```
conventionalChangelogCore([options, [context, [gitRawCommitsOpts, [parserOpts, [writerOpts]]]]])
```

```
 parserOpts = data.parserOpts 
 writerOpts = data.writerOpts 
  
 gitRawCommits(gitRawCommitsOpts, gitRawCommitsOpts) 
   .on('error', function (err) { 
     err.message = 'Error in git-raw-commits: ' + err.message 
```

**Comment by axetroy** [comment]
### Option 3.

add `rawExecOpts` property to `gitRawCommitsOpts`

The current API remains unchanged.

```
conventionalChangelogCore([options, [context, [gitRawCommitsOpts, [parserOpts, [writerOpts]]]]])
```

```diff
 parserOpts = data.parserOpts
 writerOpts = data.writerOpts

-  gitRawCommits(gitRawCommitsOpts)
+  gitRawCommits(gitRawCommitsOpts, gitRawCommitsOpts.rawExecOpts)
   .on('error', function (err) {
     err.message = 'Error in git-raw-commits: ' + err.message
```

**Comment by stevemao** [comment]
I like option 1 a lot better. I think a breaking change is fine and it should be easy for users to change accordingly.

**Comment by hutson** [comment]
I've come to prefer the single object argument as well for most of my work. I can always do object destructuring in the called function if I want to pull out specific properties from the object (typically I do this for readability).

**Comment by vivaxy** [comment]
Already implemented at https://github.com/conventional-changelog/conventional-changelog/pull/480

**Comment by axetroy** [comment]
@vivaxy 
Thanks for telling me this.

and I think I can close this issue
