### ISSUE TITLE
Render commit body instead of subject for changelog

### ISSUE THREAD

**Issue by renestalder** [conventional-changelog/conventional-changelog#423]
The usual approach of using the subject as the entry in the changelog fits most technical projects. But in projects where the end product is delivered to the client, the commit subject describing the "what" in a very short, technical manner, will not say much about what changed for the end-user.

As the commit body describes the "why" of a commit, my team and I often use it to describe the change in a user friendly, non-technical way. In these cases, it would be convenient to generate the changelog from the commit bodies, instead the commit subjects.

Is there an easy way to make this happen?

**Comment by stevemao** [comment]
Yes, you can tweak the template of the writer: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer#commitpartial

**Comment by renestalder** [comment]
@stevemao Just saw this is still open, but I feel like you answered my question pretty much. Closing.

Thank you.
