### ISSUE TITLE
conventionalcommits preset

### ISSUE THREAD

**Issue by onrige** [conventional-changelog/conventional-changelog#431]
Hi
Recently you added a new preset [`conventional-changelog-conventionalcommits`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) in [this commit](f2fb240391e10c79756a590eb6aea1e235ccb0a2) but it does not published yet
Have you any plans on this in near future?

Thanks

**Comment by stevemao** [comment]
Hi
You can join the slack channel https://github.com/conventional-changelog/conventional-changelog#conventional-changelog to ask questions and you'll get faster responses too. Thanks

**Comment by onrige** [comment]
@stevemao So after two days there is no response...thanks again :)
