### ISSUE TITLE
conventional-changelog-conventionalcommits requires Node 10?

### ISSUE THREAD

**Issue by omghax** [conventional-changelog/conventional-changelog#436]
I recently started seeing [CI failures](https://travis-ci.org/omghax/ember-mock-socket-shim/jobs/519188552#L518) in a project that uses [`standard-version`](https://github.com/conventional-changelog/standard-version), seemingly because `conventional-changelog-conventionalcommits` [requires Node 10 or greater](https://github.com/conventional-changelog/conventional-changelog/blob/e84a647b5884eaa3eb6324853fd026c29629e600/packages/conventional-changelog-conventionalcommits/package.json#L28). The output from Yarn is:

```
error conventional-changelog-conventionalcommits@1.1.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "6.17.1"
```

The same thing happens locally if I try to run `yarn upgrade standard-version`. The other packages in this repo specify `>= 6.9.0` in their `engines` field. Is there a reason this one requires a different version?

**Comment by Disco-Pope** [comment]
Came here to point out the same issue. Conventional-changelog-cli is suddenly broken back to 2.0.6 if you're on node 8

**Comment by savokiss** [comment]
Same issue, can't use `standard-version` now.

**Comment by brendanmc6** [comment]
Same here.

I was able to get my codeship CI builds to run again by downgrading the parent dependency (in my case) `"conventional-changelog-cli": "2.0.5"`

**Comment by ersimont** [comment]
Same issue here using `standard-version`. I'm using yarn - here is how I how I worked around it. In `package.json` add this section:
```json
  "resolutions": {
    "conventional-changelog": "^1.0.0"
  },
```

**Comment by mcrib96** [comment]
> Same issue here using `standard-version`. I'm using yarn - here is how I how I worked around it. In `package.json` add this section:
> 
> ```json
>   "resolutions": {
>     "conventional-changelog": "^1.0.0"
>   },
> ```

Thanks for providing this workaround.  Our build is able to continue gracefully now.

**Comment by KnisterPeter** [comment]
This kind of blocks using standard-version as a project dependency if you want to support different node versions. Please revert this change.
The workaround would help for now but it will result in later problems for sure.

**Comment by KnisterPeter** [comment]
@bcoe Why was this change done?

**Comment by bcoe** [comment]
@KnisterPeter @omghax I don't believe this was intentional, I'll work on getting a patch out soon.

**Comment by bcoe** [comment]
would also accept a patch that addresses the issue.
