### ISSUE TITLE
renovate bot does not seem to be running

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#445]
@hutson it seems like we have quite a few dependencies out of date, any idea why I don't see any PRs coming in from renovate bot?

**Comment by hutson** [comment]
According to [Renovate logs](https://renovatebot.com/dashboard#github/conventional-changelog/conventional-changelog/64448864) looks like we are depending on a preset package that was deleted when my old npm account was deleted.

Closing in favor of #302 (which is the automatically generated Renovate issue.
