### ISSUE TITLE
conventionalcommits preset broken

### ISSUE THREAD

**Issue by mydea** [conventional-changelog/conventional-changelog#512]
Hi,

I have just installed the latest version of this, and the `conventionalcommits` preset seems to be broken.

I did a bit of digging, and it seems to be breaking here:
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-preset-loader/index.js#L36

But `path` is always a string for me, so the callback-style here:
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/index.js

I looked into other presets, and they either take a callback only, or directly return a promise. However, they do not seem to be taking any config or so, so not sure how to fix this, as the config is used in multiple places here.

So basically, these styles seem to be working:

```js
// Angular
module.exports = Q.all([conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts])
  .spread((conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts) => {
    return { conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts }
  })

// Ember
module.exports = presetOpts

function presetOpts (cb) {
  Q.all([conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts])
    .spread((conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts) => {
      cb(null, { gitRawCommitsOpts: { noMerges: null }, conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts })
    })
}
```

But this is not working:

```js
module.exports = function (config) {
  return Q.all([
    conventionalChangelog(config),
    parserOpts(config),
    recommendedBumpOpts(config),
    writerOpts(config)
  ]).spread((conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts) => {
    return { conventionalChangelog, parserOpts, recommendedBumpOpts, writerOpts }
  })
}
```

**Comment by eshepelyuk** [comment]
Any updates on this ?

**Comment by tommywo** [comment]
I had to revert my fix, because it broke callback style presets.

**Comment by thomasbottonari** [comment]
@tommywo thanks for the fix. when can we expect a release?

**Comment by thomasbottonari** [comment]
Is there a past release that I can use in the meantime where the `conventionalcommits` preset was working? I tried a few but can't get it to output anything.

**Comment by thomasbottonari** [comment]
@tommywo can we get an update on expected release timing? I'd like to use the conventionalcommits preset with the cli to generate a changelog that has a custom config but I can't find any version where that is working. Hoping this bug fix resolves it.

**Comment by eshepelyuk** [comment]
@tommywo yes please

**Comment by tommywo** [comment]
Hi @thomasbottonari, @eshepelyuk, I've just made a release :) 
can you try `next` version `npm install -g conventional-changelog-cli@next` ?

**Comment by thomasbottonari** [comment]
@tommywo that seems to be working for me. One thing I haven't been able to figure out from reading the docs/code is how to pass the `conventionalcommits` preset a config object to change the `types` array for example. I'm passing a config file to the cli but can you advise on what to name the config object inside that file?

**Comment by tommywo** [comment]
@thomasbottonari I've answered you [here](https://github.com/conventional-changelog/conventional-changelog/issues/529#issuecomment-538563836)
