### ISSUE TITLE
conventional-recommended-bump stuck on major bump in CI process

### ISSUE THREAD

**Issue by alexanimal** [conventional-changelog/conventional-changelog#517]
I'm using this package in my CI process along with commitizen and it used to work perfectly, but after I added a "BREAKING CHANGE" from commitizen to one of my commits the package will only major version **EVERY SINGLE TIME**. There have been plenty of versions and releases since the "BREAKING CHANGE" commit, yet for some reason the package continually says major during the CI process. When i run the command on my local I get patch or minor, yet every single time during CI it major versions. Has anyone run into this with this package?

**Comment by tommywo** [comment]
probably you don't fetch tags on your CI
