### ISSUE TITLE
The cli is unable to be passed a preset config

### ISSUE THREAD

**Issue by thomasbottonari** [conventional-changelog/conventional-changelog#529]
According to the cli README:
> To fully customize the tool, please checkout conventional-changelog and conventional-changelog-core docs. You can find more details there. Note: config here can work with preset, which is different than options.config in conventional-changelog.
> 

However, I am not able to pass a preset config for the `conventional-changelog/conventional-changelog-conventionalcommits` preset when using the cli. I've tried passing the cli a config file using `--config`, but no matter what config params I use from the below link, I can't get the preset to change functionality.

https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

The odd thing is that I was able to get it to work when using `semantic-release/release-notes-generator` (which uses the same underlying packages). However this functionality doesn't seem to exist with the cli unless I am missing something.

**Comment by tommywo** [comment]
that's confusing because conventional-changelog-config-spec is a config spec for conventional-changelog-conventionalcommits preset and not conventional-changelog-cli config. 

You can use js config like this
```javascript
'use strict'
const config = require('conventional-changelog-conventionalcommits')

module.exports = config({
    "issuePrefixes": ["TEST-"],
    "issueUrlFormat": "example.com/{prefix}{id}"
})
```
or json config like that:
```json
{
    "options": {
        "preset": {
            "name": "conventionalchangelog",
            "issuePrefixes": ["TEST-"],
            "issueUrlFormat": "example.com/{prefix}{id}"
        }
    }
}
```

**Comment by thomasbottonari** [comment]
Thanks! I was missing the proper format for the "options" object in the json config. It might be nice to add that to the documentation.

However, I still am unable to get my issuePrefixes to work:

>             "issuePrefixes": ["'[ch'", "'[CH'", "'[Ch'"],

This is an example of the commit message that should be picking it up.

> feat(vendor-portal): add fee rate col to history invoices
> Closes [ch15409]

It is almost like it is not reading the footer of the message. Again, I was able to get this working using `semantic-release`, but the cli doesn't seem to be parsing it the same way. Am I missing some config?

**Comment by thomasbottonari** [comment]
Upon further debugging, it seems to be related to the fact that I had to wrap `[ch` in single quotes. The problem is that if I don't, it seems to be picking up on each individual character `[`, `c`, `h` and turning all of them in the message into a link.

![image](https://user-images.githubusercontent.com/5902773/66241724-ac01e400-e6cd-11e9-8b57-e356fd4ed449.png)

**Comment by tommywo** [comment]
We're joining `issuePrefixes` into a regex [here](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/lib/regex.js#L29) and `[` is a special character. Try changing it to `[[]`. You can also mess referenceActions so they would match  for example `Closes [` instead of `Closes `.

**Comment by thomasbottonari** [comment]
Ah, that makes sense. I tried with `[[]` and that certainly helped but it seems to be failing to pickup the number that follows the prefix. Maybe the `]` is breaking it? This is what I am seeing, and the link has no `id` in the issueUrl.

![image](https://user-images.githubusercontent.com/5902773/66248584-5857c080-e6f6-11e9-9ba4-acc6692c6f32.png)

**Comment by thomasbottonari** [comment]
Also, I wasn't able to get `referenceActions` to work. Do I put that in the `options` object, the `preset` object, or `parserOpts`? The documentation on the cli config seems pretty thin.

**Comment by tommywo** [comment]
try this json - seems be working with your example:
```json
{
    "options": {
        "preset": {
            "name": "conventionalcommits",
            "issueUrlFormat": "https://example.com/{{prefix}}{{id}}",
            "issuePrefixes": ["ch", "CH", "Ch"],
            "referenceActions": [
                "Closes ["
            ]
        } 
    }
}
```

**Comment by thomasbottonari** [comment]
Yes this seems to be working now! Thank you! As stated previously, I might recommend some better documentation around the cli config file.

**Comment by tommywo** [comment]
You're more then welcome to make a pull request with better documentation ;)

**Comment by thomasbottonari** [comment]
I can add the bits that I now know, but I'm sure it will be incomplete
