### ISSUE TITLE
conventional-commits-parser- Node engine incompatibility

### ISSUE THREAD

**Issue by StarpTech** [conventional-changelog/conventional-changelog#533]
The `conventional-commits-parser` supports Node > 6 but use a package called [is-text-path](https://github.com/sindresorhus/is-text-path) which required Node >= 8. This produce an error at installing with yarn.

**Comment by tommywo** [comment]
According to our [node support policy](https://github.com/conventional-changelog/conventional-changelog#node-support-policy) node 6 should be removed from supported node versions.

**Comment by StarpTech** [comment]
Then you should update the engine property and release a major update.

**Comment by StarpTech** [comment]
Here you read that official guideline. This package should bump a major before relying on other nodejs versions. 

https://github.com/nodejs/package-maintenance/blob/master/docs/versioning.md#other-versioning-requirements

> Increasing the minimum required version of node is a breaking change and should be accompanied by major semver change.

**Comment by tommywo** [comment]
I've downgraded is-text-path. Release is on `@next` tag

**Comment by StarpTech** [comment]
@tommywo thank you.
