### ISSUE TITLE
CLI: would it be worth adding a version prefix option?

### ISSUE THREAD

**Issue by dora-gt** [conventional-changelog/conventional-changelog#538]
Hi,

I'm using [`cargo release`](https://github.com/sunng87/cargo-release) for a Rust project. It tags with a version prefixed name like `some-crate-v1.0.0` when it is used in a `workspace`. So this is incompatible with `conventional-changelog`.

Would it be worth adding a version prefix option? If I could pass `some-crate-` as a version prefix, `conventional-changelog` would process the tags properly.

Or should I push a tag which contains just only a semantic version like `v1.0.0`?

**Comment by tommywo** [comment]
Hi, this is already available.
https://github.com/conventional-changelog/conventional-changelog/blob/86ae571027a23de4325499b1eab0ad9d26429ea3/packages/conventional-changelog-cli/cli.js#L50

**Comment by dora-gt** [comment]
@tommywo oops!! I'm sorry I overlooked that! Thank you so much🙇‍♂️
