### ISSUE TITLE
conventional-commits-parser: Not parsing default separator

### ISSUE THREAD

**Issue by meriley** [conventional-changelog/conventional-changelog#539]
The documentation states that the CLI should be able to seperate on `\n\n\n`

I have the file structured as

`
\n\n\nfix(title): a title is fixed\n\n\nfeat(ngMessages): provide support for dynamic message resolution\n\n\n
`

and when I run the command `cat ./test.txt | conventional-commits-parser` I see the output:

`[
{"type":"fix","scope":"title","subject":"a title is fixed","merge":null,"header":"fix(title): a title is fixed","body":"feat(ngMessages): provide support for dynamic message resolution","footer":null,"notes":[],"references":[],"mentions":[],"revert":null}
]
`

It is treating the second item as a body instead of a separate entry.

**Comment by meriley** [comment]
The issue appears to be at
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/cli.js#L140

I believe this should be:
`process.stdin
    .pipe(split(separator)) // <-- Note 
    .pipe(conventionalCommitsParser(options))
    .on('error', function (err) {
      console.error(err.toString())
      process.exit(1)
    })
    .pipe(JSONStream.stringify())
    .pipe(process.stdout)`

**Comment by tommywo** [comment]
Hi @meriley. 
It looks like you are on track. Would you like to make a PR with this change and relevant unit test?
