### ISSUE TITLE
Old messages included in generated

### ISSUE THREAD

**Issue by wintercounter** [conventional-changelog/conventional-changelog#555]
Generating change-log will sometimes include old commit messages from previous releases resulting also in wrong version bumping. These repos are used by multiple developers and I'm trying to find out where the whole thing is going wrong.

**Comment by tommywo** [comment]
Hi @wintercounter 
Can you point out an example occurrence of this or provide reproducible test case?

**Comment by tommywo** [comment]
Including old commits should be fixed with pr #557, but that doesn't affect version bumping.
