### ISSUE TITLE
[Question] multiple changelogs - monorepo

### ISSUE THREAD

**Issue by enterprisebug** [conventional-changelog/conventional-changelog#556]
Assume the following folder structure

- repo
  - microservice1
  - microservice2

is it possible to have a dedicated changelog for `microservice1` and `micoservice2` ?

At the moment i only see that the changelogs of the two micoservices are combined into one.

**Comment by stevemao** [comment]
lerna should be able to do that.

**Comment by tommywo** [comment]
`conventional-changelog-cli` has `--commit-path` for that for that so you don't have to use lerna. Example usage with lerna is here https://github.com/lerna/lerna/tree/master/commands/version#generating-initial-changelogs
