### ISSUE TITLE
Backfill / regenerate option

### ISSUE THREAD

**Issue by wyardley** [conventional-changelog/conventional-changelog#584]
It would be extremely nice to have an option to backfill / regenerate changelog based on tags.

Specifically, I'd like to be able to do something like `auto-changelog` or `github_changelog_generator`, but with the ability to follow conventional / angular style commits where they exist. Currently, if I run the tool against a project which has been using these conventions for a while, but hasn't yet been configured to use semantic-release, it will end up generating everything under the most recent tag. Is there a way to do this currently?

I tried stepping through each tag and re-running, but (maybe I was doing it wrong) that didn't seem to work either, even with the append option.

**Comment by wyardley** [comment]
Maybe similar to #571? I tried putting in a fake `package.json` with version set (this is not a node project), but that didn't seem to help.

**Comment by patrickcate** [comment]
I'd love this feature as well.

**Comment by wyardley** [comment]
I realized that this _is_ a documented feature, albeit one that’s not working for my specific use case, so going to close in favor of #571

**Comment by swernerx** [comment]
I wonder where you @wyardley  see that this is how it's documented. I understand the `releaseCount` option: `If 0, the whole changelog will be regenerated and the outfile will be overwritten` (from CLI) to be exactly what I need. But it does not seem to work.

**Comment by wyardley** [comment]
@swernerx:
> I wonder where you @wyardley see that this is how it's documented.

Sorry, I was referring to the link I posted above:
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#quick-start

**Comment by swernerx** [comment]
That's exactly what I feel. Generating previous changelogs one could assume that it generates each of the previous entries... instead of putting everything into one.
