### ISSUE TITLE
Update "meow" dependency to >=6.1.0 to fix npm audit vulnerability in yargs-parser

### ISSUE THREAD

**Issue by fabb** [conventional-changelog/conventional-changelog#633]
There is an npm audit error in `yargs-parser`: https://www.npmjs.com/advisories/1500

`meow` updated to a non-affected version in 6.1.0: https://github.com/sindresorhus/meow/tree/v6.1.0

Please update the `meow` dependency to fix the npm audit error.

Note that I'm aware that the maintainer of the `meow` project stated that the specific vulnerability won't affect `meow`, but since `npm audit` cannot distinguish that, and we use it to fail vulnerable builds, it would be helpful to fix it nonetheless.

**Comment by fabb** [comment]
Note that the dependencies `get-pkg-repo`, `git-semver-tags` and `git-raw-commits` seem to have an old version of `meow` as a transitive dependency too.

**Comment by gbhasha** [comment]
Same vulnerability found in  @commitlint/cli > @commitlint/lint > @commitlint/parse >     │
│               │ conventional-commits-parser > meow > yargs-parser  

For detailed report:
https://snyk.io/test/npm/conventional-commits-parser
