### ISSUE TITLE
repeating all commits in upcoming version

### ISSUE THREAD

**Issue by indraraj26** [conventional-changelog/conventional-changelog#634]
```
  "conventional-changelog": "conventional-changelog",
    "release": "conventional-changelog -p angular -i CHANGELOG.md -s"
```

With this every upcoming version still i do get old commits which was in old version. How can we avoid ? I want changelog should write what changes in this version?

output in changelog
```
## 0.0.8 (2020-04-29)

### Bug Fixes

* text edd1937


### Features

* cosmatic changes eeba0c3
* first-commit c7c6c98
* test 01ab25f
* test2 04cf4v4

## 0.0.7 (2020-04-29)

### Bug Fixes

* text edd1937


### Features

* cosmatic changes eeba0c3
* first-commit c7c6c98
* test 01ab25f
```

**Comment by werts** [comment]
The same

**Comment by elva329** [comment]
What is the solution for this issue ?

**Comment by yarastqt** [comment]
I have same problem, anyone know how to fix this issue?

**Comment by werts** [comment]
@yarastqt @elva329 hi,I have solved this problem, after every building, i create a new tag, and then the changes only append to earlier tags.another thing is: you can make use of tag,and group some changes into one tag.

**Comment by elva329** [comment]
> @yarastqt @elva329 hi,I have solved this problem, after every building, i create a new tag, and then the changes only append to earlier tags.another thing is: you can make use of tag,and group some changes into one tag.

Thanks for your idea, but could you be more specific? Any example commands?
