### ISSUE TITLE
PSA: if you need to release from this repo

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#641]
Just had a heck of a time releasing some patches related to recent security issues (_releasing this repo in general is unfortunately a bit painful, due to being mono repo_).

Here's some tips on doing so:

1. it's probably worth coordinating the release [here](http://devtoolscommunity.herokuapp.com/).
2. don't release individual libraries, run `npm run release` in the root directory.

**Comment by bcoe** [comment]
Publication is now automated using release-please.

**Comment by banli17** [comment]
hi,  May I ask a monoreop release issue, do I need to manually tag the changed packages when the warehouse releases the version?
