### ISSUE TITLE
It looks like node 8 was dropped in a patch release

### ISSUE THREAD

**Issue by kellyselden** [conventional-changelog/conventional-changelog#644]
https://github.com/conventional-changelog/conventional-changelog/pull/599

Now getting the following in CI `error conventional-recommended-bump@6.0.9: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"`

**Comment by stevemao** [comment]
Maybe publish error. There's a "!" in the commit message so they are supposed to be a major release.

**Comment by Julusian** [comment]
I guess this might be because the version numbers were manually incremented by a patch number after that commit eg: https://github.com/conventional-changelog/conventional-changelog/commits/master/packages/conventional-changelog-angular/package.json

**Comment by natlang** [comment]
> #599
> 
> Now getting the following in CI `error conventional-recommended-bump@6.0.9: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"`

I'm having the same issue as well - for `git-raw-commits` and `conventional-commits-parser`. 
The following resolves the issue:
```
  "resolutions": {
    "git-raw-commits": "2.0.3",
    "conventional-commits-parser": "3.0.8"
  }
```
Instead of 2.0.7 and 3.1.0 respectively.
Looks like it is a publish error, a breaking change such as this should be a major version bump, not a patch/minor version upgrade.

**Comment by G-Rath** [comment]
Any chance of getting a patch release reverting this breaking change?

**Comment by alasdairhurst** [comment]
Definitely an issue, but it's been a while now. Not sure who can help here, maybe @bcoe?

**Comment by bcoe** [comment]
It's unfortunately that this happened, but it's been 6 months, and I don't think we're going to take the time to revert this change.

There's a very limited number of hours that folks are currently contributing to this project I'm afraid.

**Comment by bcoe** [comment]
@alasdairhurst Node 8 has been EOL for quite some time, curious if there's a specific dependency that's causing this alert for you?

**Comment by Julusian** [comment]
To make standard-version 7.x work in node 8, we had to use yarn resolutions to pin the following. Going any newer in the semver range defined by the calling package would try to use a version with the engine error.
```
"resolutions": {
    "**/conventional-changelog-angular": "5.0.6",
    "**/conventional-changelog-atom": "2.0.3",
    "**/conventional-changelog-codemirror": "2.0.3",
    "**/conventional-changelog-core": "4.1.3",
    "**/conventional-changelog-conventionalcommits": "4.2.3",
    "**/conventional-changelog-ember": "2.0.4",
    "**/conventional-changelog-eslint": "3.0.4",
    "**/conventional-changelog-express": "2.0.1",
    "**/conventional-changelog-jshint": "2.0.3",
    "**/conventional-changelog-preset-loader": "2.3.0",
    "**/conventional-changelog-writer": "4.0.11",
    "**/conventional-commits-filter": "2.0.2",
    "**/conventional-commits-parser": "3.0.8"
  }
```

**Comment by bcoe** [comment]
@Julusian we have ` --engine-strict` in the options now for npm install, which should help prevent this from cropping up in the future.
