### ISSUE TITLE
Ticket "numbers" should support letters

### ISSUE THREAD

**Issue by mdnorman** [conventional-changelog/conventional-changelog#650]
I'm using a ticketing system for some personal project, and the ticket numbers start with a hash `#` and include letters, eg `#7a1310`. The ticket prefix works great. However, the ticket number links in my `CHANGELOG.md` exclude anything after the numeric part, eg `(#7)[issue link]a1310`.

The ticketing system is https://app.clickup.com/ if you're interested.

**Comment by diminutivesloop** [comment]
We use Trello for issue tracking and have the same problem.

**Comment by kerryj89** [comment]
Sad that this isn't doable yet.  I wish they would allow us to write the pattern beyond the prefix.

**Comment by gastonsilva** [comment]
+1

**Comment by sebastiansanio** [comment]
+1

**Comment by kingpeti** [comment]
+1
