### ISSUE TITLE
Please release 5.0.11

### ISSUE THREAD

**Issue by lukiano** [conventional-changelog/conventional-changelog#658]
The dot-prop vulnerability has been addressed on the master branch but it seems was never released.

**Comment by lukiano** [comment]
Let me add more information to my request:
It looks like the version 5.0.11 of the package `conventional-changelog-angular` wasn't published to the NPM repo. Digging further I see that something failed in https://github.com/conventional-changelog/conventional-changelog/commit/3dedddc397e7cbcf5a2ff971ca933992b9e4d11f , and when opening https://github.com/conventional-changelog/conventional-changelog/runs/789839009 I can see a timeout when collecting coverage for the Windows build.

**Comment by fernandopasik** [comment]
compare-func v1 has some dependencies with vulnerabilities, it would be great to update and release asap.

**Comment by lukiano** [comment]
I could find that 5.0.11 was published but tagged with "next", so "^5.0.0" is not finding it. 

An explicit entry in the resolutions field of my package.json file did the trick, even if not the ideal solution.

**Comment by webmaster128** [comment]
The same applies for `conventional-changelog-writer`.

```
  "resolutions": {
    "conventional-changelog-angular": "^5.0.11",
    "conventional-changelog-writer": "^4.0.17"
  }
```

does the job in my project. It would be nice to get those patches on the default release branch on npm :)

**Comment by JanAmbrozic** [comment]
Thanks @webmaster128, I used your solution and it solves my dot-prop vulnerability issue. Good enough for now :)

**Comment by safaiyeh** [comment]
@bcoe Could we get a proper release of conventional-changelog-angular & conventional-changelog-writer the security warning is been a blocker for my project.

**Comment by danmana** [comment]
All of these look like they are tagged with `next` instead of `latest`
```
conventional-changelog-angular@5.0.11
conventional-changelog-conventionalcommits@4.3.1
conventional-changelog-jshint@2.0.8
conventional-changelog-writer@4.0.17
```

There are probably others, but these were the ones I had to update to get rid of dot-props

**Comment by bcoe** [comment]
@danmana @safaiyeh @lukiano, all versions have been updated to latest:

```
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 91 scanned packages
```
