### ISSUE TITLE
reduce the multiple blanks between the version title and the section title

### ISSUE THREAD

**Issue by yi-Xu-0100** [conventional-changelog/conventional-changelog#763]
Why not update to reduce the multiple blanks between the version title and the section title? 😀

It generate the changelog like follow: 
```md
## 0.0.1 "this is a title" (2015-05-29)


### Features
```

It causes the MD012 problem for [markdownlint](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md021). 😥

This may not trigger a display error. Multiple-blanks in markdown default show as the one line in preview. 🤔

But I think it can make better. 😁

**Comment by gian1200** [comment]
Seems to be already fixed on [conventional-changelog-conventionalcommits: v8.0.0](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v8.0.0)

https://github.com/conventional-changelog/conventional-changelog/issues/1188
