### ISSUE TITLE
More hosts

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/conventional-changelog#80]
~~Some people mentioned JIRA~~

CC @rsids @bennekrouf @z0r1k 

bitbucket is partially supported apparently.

**Comment by rsids** [comment]
JIRA is selfhosted, so it will be hard to support it out of the box

**Comment by stevemao** [comment]
cc @Rauno56

**Comment by destroyerofbuilds** [comment]
On-premise GitLab.

**Comment by stevemao** [comment]
Just an update: JIRA is not a host and it is supported now.
Any other hosts are welcome.

**Comment by admosity** [comment]
Saw #87 linking to here. Experiencing it with standard-changelog 1.0.1 

Am I missing some steps/can someone point me to where I should add this implementation?

Thanks!

**Comment by stevemao** [comment]
@etremblay see #185

**Comment by admosity** [comment]
@stevemao thanks, will check it out when i get a chance

**Comment by admosity** [comment]
@stevemao PR submitted!

**Comment by hbetts** [comment]
Closing out. Looks like there's work to improve how we manage the templates in pull request #187.

However, this issue is really generic. If someone has a specific host they would like added, or there is a host we can support _better_, please feel free to open a new issue.
