### ISSUE TITLE
Replace dateFormat \w vanila

### ISSUE THREAD

**Issue by jimmywarting** [conventional-changelog/conventional-changelog#833]
https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-changelog-writer/index.js#L15

```js
date: new Date().toJSON().slice(0, 10) // much faster
```

**Comment by csimi** [comment]
It's not only faster but `// sv-SEis used for yyyy-mm-dd format` seems to be incorrect on Windows 10 and Node 21
It doesn't zerofill for me, so what I'm getting is `2024-3-1`

There's no need to go through the hell that is Intl when a simple `toISOString()` or `toJSON()` with slice works just as well.

**Comment by dangreen** [comment]
https://github.com/conventional-changelog/conventional-changelog/commit/8c4bbbe2945a23bd3660a2dbfe1b497fda03afa4#diff-69723b6aad1d93c3d2e8c760193d2d35f6a25caa3860830fa60a4bf6d16a4667R13
