### ISSUE TITLE
conventional-changelog-conventionalcommits: Patch version headings shouldn’t be a different size

### ISSUE THREAD

**Issue by shivjm** [conventional-changelog/conventional-changelog#867]
Same as #214, but for conventional-changelog-conventionalcommits. Heading levels indicate a structure. Patch versions should use `## <small>` instead of `### ` , as @marcysutton pointed out.

**Comment by trallnag** [comment]
Is this a regression? The following link points to a changelog where the heading level structure is correct. Scroll down a bit to see patch releases.

* <https://github.com/oleg-koval/semantic-release-npm-github-publish/blob/master/CHANGELOG.md>

His package.json looks quite different from mine:

* https://github.com/oleg-koval/semantic-release-npm-github-publish/blob/master/package.json

I also noticed the heading level structure and posted about it here <https://github.com/semantic-release/semantic-release/discussions/2312>.

**Comment by shivjm** [comment]
> The following link points to a changelog where the heading level structure is correct. Scroll down a bit to see patch releases.
> 
> * https://github.com/oleg-koval/semantic-release-npm-github-publish/blob/master/CHANGELOG.md

Sorry, I’m not sure I follow—all the releases there seem to follow the incorrect pattern of smaller headings for patch versions and larger headings for major versions. 😖

**Comment by trallnag** [comment]
@shivjm, okay I see what you mean. His [changelog](https://github.com/oleg-koval/semantic-release-npm-github-publish/blob/2a9ee835283c85da53e23a5c21062154e5f88b7d/CHANGELOG.md):

* `#` for major and minor releases
* `##` for patch releases
* `###` for "types" (bugs, features, ...)

In [my changelog](https://github.com/trallnag/ansible-role-asdf-plugin/blob/5ac19749322d0ada0a582987227b8218dc07dd48/CHANGELOG.md):

* `##` for major and minor releases
* `###` for patch releases
* `###` for "types" (bugs, features, ...)

**Comment by shivjm** [comment]
Correct, that’s the current situation. What I’m talking about is changing it to always use `##` and add `<small>` for patch releases.

**Comment by trallnag** [comment]
I agree

**Comment by languitar** [comment]
Actually, the whole idea of using higher-level headings for major releases is a bit strange here, because a heading in a text document is meant for what follow below. However, with the reverse sorting, the structure created here puts the previous releases into the section created by the next version, e.g.:

```markdown
## 2.3.0

# 2.0.0

## 1.5.18

## 1.5.17
```

Why are 1.5.17 and 1.5.18 part of the section opened by the 2.0.0 heading. That doesn't make any sense with this sorting.

**Comment by kleinfreund** [comment]
Even without reverse sorting, it doesn’t make sense to use subordinate heading levels for minor or patch versions. Version 2.0.1 does not belong to or is not a part of version 2.0.0. They are simply separate versions of which 2.0.1 is the newer one. Version 2.0.1 can be considered a part of some notion of a version 2 release line, but there are no sections for such a thing in the changelog templates referenced here. The sections are always for exact versions associated with an individual release and should therefore all have the exact same heading level.

**Comment by chalkygames123** [comment]
Thank you all. I've been waiting for this fix!
