### ISSUE TITLE
[Release-notes-generator]: conventional-changelog: Override dateformat

### ISSUE THREAD

**Issue by ciltocruz** [conventional-changelog/conventional-changelog#922]
Hello, this is related to #243 but I don't write there because the thread has been closed for 5 years.

So sorry for opening this 5 years later. I've searched everywhere but I can't find an example or a way to replace context variables. I would like to change the date format that appears in the changelog, but the "date" property inside "writerOpts" or "presetConfig" or anywhere doesn't work.

Is there a way to change it?

I use the preset: `conventionalcommits`.

If you need my `.releasetc.js` file let me know.

Thank you!

**Comment by Duduzera1997** [comment]
Hello! 🤙🏼

After many attempts I managed to change using **finalizeContext**, view this code:

```
writerOpts: {
  finalizeContext: (context) => {
    context.date = 'You Date :D';
    return context;
  },
},
```

Maybe [this file](https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-changelog-writer/index.js) will help you more than the documentation itself if your knowledge with javascript is average.

Good luck!

**Comment by ciltocruz** [comment]
Oh. Nice!
I hadn't found that property and I've been reading about it for days.
Thank you!

I've tried it, but I've had a problem. I have tried to use `dateformat` in my file but the project is not npm, this is running only in CI and I can't use `require` in my file because I don't want to have npm modules in my project just for this.
I have opted for the classic solution:

```
writerOpts: {
  finalizeContext: (context) => {
       let date = new Date()
       let day = `${(date.getDate())}`.padStart(2,'0');
       let month = `${(date.getMonth()+1)}`.padStart(2,'0');
       let year = date.getFullYear();
       context.date = day + '-' + month + '-' + year;
       return context;
  },
},
```

And it has worked perfectly. Thank you very much for your help.

I close this issue.
