### ISSUE TITLE
Please make a release of conventional-changelog with conventional-changelog-conventionalcommits v5.0.0

### ISSUE THREAD

**Issue by matatk** [conventional-changelog/conventional-changelog#940]
The fix in [conventional-changelog-conventionalcommits v5.0.0](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v5.0.0) is something I'd really like to benefit from in my projects. I'm using it via https://github.com/release-it/conventional-changelog, which depends on conventional-changelog 3.1.25. However, v3.1.25 of conventional-changelog does not require v5.0.0 of conventional-changelog-conventionalcommits (it depends on v4.5.0).

Please could you bump conventional-changelog to include conventional-changelog-conventionalcommits v5.0.0? Thanks in advance, and for your work on this project.

**Comment by matatk** [comment]
In the meantime, I found that it's [possible to use `overrides` in `package.json` to force this new version to be used](https://stackoverflow.com/a/70396201/1485308). I've _just_ tried it out, and it seems to be working so far.

**Comment by wesleyboar** [comment]
I second this request, but **also** request the version update be even further, to https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-conventionalcommits-v6.1.0.

**Comment by dangreen** [comment]
Hi all.

Latest conventional-changelog version depends on latest conventional-changelog-conventionalcommits version

https://unpkg.com/browse/conventional-changelog@4.0.0/package.json
https://unpkg.com/browse/conventional-changelog-conventionalcommits@6.1.0/package.json

**Comment by wesleyboar** [comment]
Thanks. After posting, I started to think so, but I had trouble following and verifying the dependency chain.

Does that mean this issue can be closed? Do we wait for that to be done by someone with permission to do so?
