### ISSUE TITLE
conventionalcommits wrtierOpts doesn't fully merge user config with defaults

### ISSUE THREAD

**Issue by mattclough1** [conventional-changelog/conventional-changelog#983]
In [this section of writer-opts.js](https://github.com/conventional-changelog/conventional-changelog/blob/58f0887283a200d52e49607baf7b352f26177b05/packages/conventional-changelog-conventionalcommits/writer-opts.js#L178-L194), the comment indicates that user configs should be merged with the defaults, but, for example (also linked)
```js
// merge user set configuration with default configuration.
function defaultConfig (config) {
  config = config || {}
  config.types = config.types || [
    { type: 'feat', section: 'Features' },
    { type: 'feature', section: 'Features' },
    { type: 'fix', section: 'Bug Fixes' },
    { type: 'perf', section: 'Performance Improvements' },
    { type: 'revert', section: 'Reverts' },
    { type: 'docs', section: 'Documentation', hidden: true },
    { type: 'style', section: 'Styles', hidden: true },
    { type: 'chore', section: 'Miscellaneous Chores', hidden: true },
    { type: 'refactor', section: 'Code Refactoring', hidden: true },
    { type: 'test', section: 'Tests', hidden: true },
    { type: 'build', section: 'Build System', hidden: true },
    { type: 'ci', section: 'Continuous Integration', hidden: true }
  ]
```
`config.types` is set to only the user-defined types if they exist, or the defaults. This means if the user defines _any_ type, they'll have define _every_ type

**Comment by dangreen** [comment]
Resolved in https://github.com/conventional-changelog/conventional-changelog/pull/1064
